// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents the Billable SKU information.
public struct BillableSku: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Resource name of Billable SKU. Format:
  /// billableSkus/{sku}.
  /// Example:
  /// billableSkus/6E1B-6634-470F".
  public var sku: Swift.String = Swift.String()

  /// Unique human readable name for the SKU.
  public var skuDisplayName: Swift.String = Swift.String()

  /// Resource name of Service which contains Repricing SKU. Format:
  /// services/{service}.
  /// Example:
  /// "services/B7D9-FDCB-15D8".
  public var service: Swift.String = Swift.String()

  /// Unique human readable name for the Service.
  public var serviceDisplayName: Swift.String = Swift.String()

  /// Initialize a new instance of `BillableSku`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BillableSku().with { $0.sku = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.BillableSku"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
