// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for
/// [CloudChannelService.ChangeOffer][google.cloud.channel.v1.CloudChannelService.ChangeOffer].
///
/// [google.cloud.channel.v1.CloudChannelService.ChangeOffer]: <doc:CloudChannelServiceClient/changeOffer(request:options:)>
public struct ChangeOfferRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the entitlement to update.
  /// Name uses the format:
  /// accounts/{account_id}/customers/{customer_id}/entitlements/{entitlement_id}
  public var name: Swift.String = Swift.String()

  /// Required. New Offer.
  /// Format: accounts/{account_id}/offers/{offer_id}.
  public var offer: Swift.String = Swift.String()

  /// Optional. Parameters needed to purchase the Offer. To view the available
  /// Parameters refer to the
  /// [Offer.parameter_definitions][google.cloud.channel.v1.Offer.parameter_definitions]
  /// from the desired offer.
  ///
  /// [google.cloud.channel.v1.Offer.parameter_definitions]: <doc:Offer/parameterDefinitions>
  public var parameters: [Parameter] = []

  /// Optional. Purchase order id provided by the reseller.
  public var purchaseOrderId: Swift.String = Swift.String()

  /// Optional. You can specify an optional unique request ID, and if you need to
  /// retry your request, the server will know to ignore the request if it's
  /// complete.
  ///
  /// For example, you make an initial request and the request times out. If you
  /// make the request again with the same request ID, the server can check if
  /// it received the original operation with the same request ID. If it did, it
  /// will ignore the second request.
  ///
  /// The request ID must be a valid [UUID](https://tools.ietf.org/html/rfc4122)
  /// with the exception that zero UUID is not supported
  /// (`00000000-0000-0000-0000-000000000000`).
  public var requestId: Swift.String = Swift.String()

  /// Optional. The billing account resource name that is used to pay for this
  /// entitlement when setting up billing on a trial subscription.
  ///
  /// This field is only relevant for multi-currency accounts. It should be
  /// left empty for single currency accounts.
  public var billingAccount: Swift.String = Swift.String()

  /// Optional. Price reference ID for the offer. Only for offers that require
  /// additional price information. Used to guarantee that the pricing is
  /// consistent between quoting the offer and placing the order.
  public var priceReferenceId: Swift.String = Swift.String()

  /// Initialize a new instance of `ChangeOfferRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ChangeOfferRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ChangeOfferRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
