// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Entity representing a link between distributors and their indirect
/// resellers in an n-tier resale channel.
public struct ChannelPartnerLink: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Resource name for the channel partner link, in the format
  /// accounts/{account_id}/channelPartnerLinks/{id}.
  public var name: Swift.String = Swift.String()

  /// Required. Cloud Identity ID of the linked reseller.
  public var resellerCloudIdentityId: Swift.String = Swift.String()

  /// Required. State of the channel partner link.
  public var linkState: ChannelPartnerLinkState = ChannelPartnerLinkState()

  /// Output only. URI of the web page where partner accepts the link invitation.
  public var inviteLinkUri: Swift.String = Swift.String()

  /// Output only. Timestamp of when the channel partner link is created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Timestamp of when the channel partner link is updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Public identifier that a customer must use to generate a
  /// transfer token to move to this distributor-reseller combination.
  public var publicId: Swift.String = Swift.String()

  /// Output only. Cloud Identity info of the channel partner (IR).
  public var channelPartnerCloudIdentityInfo: CloudIdentityInfo? = nil

  /// Initialize a new instance of `ChannelPartnerLink`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ChannelPartnerLink().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ChannelPartnerLink"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
