// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [CloudChannelService.ChangeParameters][google.cloud.channel.v1.CloudChannelService.ChangeParameters].
///
/// [google.cloud.channel.v1.CloudChannelService.ChangeParameters]: <doc:CloudChannelServiceClient/changeParameters(request:options:)>
public struct ChangeParametersRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the entitlement to update.
  /// Name uses the format:
  /// accounts/{account_id}/customers/{customer_id}/entitlements/{entitlement_id}
  public var name: Swift.String = Swift.String()

  /// Required. Entitlement parameters to update. You can only change editable
  /// parameters.
  ///
  /// To view the available Parameters for a request, refer to the
  /// [Offer.parameter_definitions][google.cloud.channel.v1.Offer.parameter_definitions]
  /// from the desired offer.
  ///
  /// [google.cloud.channel.v1.Offer.parameter_definitions]: <doc:Offer/parameterDefinitions>
  public var parameters: [Parameter] = []

  /// Optional. You can specify an optional unique request ID, and if you need to
  /// retry your request, the server will know to ignore the request if it's
  /// complete.
  ///
  /// For example, you make an initial request and the request times out. If you
  /// make the request again with the same request ID, the server can check if
  /// it received the original operation with the same request ID. If it did, it
  /// will ignore the second request.
  ///
  /// The request ID must be a valid [UUID](https://tools.ietf.org/html/rfc4122)
  /// with the exception that zero UUID is not supported
  /// (`00000000-0000-0000-0000-000000000000`).
  public var requestId: Swift.String = Swift.String()

  /// Optional. Purchase order ID provided by the reseller.
  public var purchaseOrderId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ChangeParametersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ChangeParametersRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let parameters = CodingKeys(stringValue: "parameters")
    static let requestId = CodingKeys(stringValue: "requestId")
    static let purchaseOrderId = CodingKeys(stringValue: "purchaseOrderId")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "parameters",
      "requestId",
      "purchaseOrderId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent([Parameter].self, forKey: .parameters) {
      self.parameters = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .purchaseOrderId) {
      self.purchaseOrderId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.parameters, forKey: .parameters)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encode(self.purchaseOrderId, forKey: .purchaseOrderId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ChangeParametersRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
