// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Entity representing a link between distributors and their indirect
/// resellers in an n-tier resale channel.
public struct ChannelPartnerLink: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Resource name for the channel partner link, in the format
  /// accounts/{account_id}/channelPartnerLinks/{id}.
  public var name: Swift.String = Swift.String()

  /// Required. Cloud Identity ID of the linked reseller.
  public var resellerCloudIdentityId: Swift.String = Swift.String()

  /// Required. State of the channel partner link.
  public var linkState: ChannelPartnerLinkState = ChannelPartnerLinkState()

  /// Output only. URI of the web page where partner accepts the link invitation.
  public var inviteLinkUri: Swift.String = Swift.String()

  /// Output only. Timestamp of when the channel partner link is created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. Timestamp of when the channel partner link is updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. Public identifier that a customer must use to generate a
  /// transfer token to move to this distributor-reseller combination.
  public var publicId: Swift.String = Swift.String()

  /// Output only. Cloud Identity info of the channel partner (IR).
  public var channelPartnerCloudIdentityInfo: CloudIdentityInfo? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ChannelPartnerLink`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ChannelPartnerLink().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let resellerCloudIdentityId = CodingKeys(stringValue: "resellerCloudIdentityId")
    static let linkState = CodingKeys(stringValue: "linkState")
    static let inviteLinkUri = CodingKeys(stringValue: "inviteLinkUri")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let publicId = CodingKeys(stringValue: "publicId")
    static let channelPartnerCloudIdentityInfo = CodingKeys(
      stringValue: "channelPartnerCloudIdentityInfo")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "resellerCloudIdentityId",
      "linkState",
      "inviteLinkUri",
      "createTime",
      "updateTime",
      "publicId",
      "channelPartnerCloudIdentityInfo",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .resellerCloudIdentityId)
    {
      self.resellerCloudIdentityId = value
    }
    if let value = try container.decodeIfPresent(ChannelPartnerLinkState.self, forKey: .linkState) {
      self.linkState = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inviteLinkUri) {
      self.inviteLinkUri = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .publicId) {
      self.publicId = value
    }
    self.channelPartnerCloudIdentityInfo = try container.decodeIfPresent(
      CloudIdentityInfo.self, forKey: .channelPartnerCloudIdentityInfo)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.resellerCloudIdentityId, forKey: .resellerCloudIdentityId)
    try container.encode(self.linkState, forKey: .linkState)
    try container.encode(self.inviteLinkUri, forKey: .inviteLinkUri)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.publicId, forKey: .publicId)
    try container.encodeIfPresent(
      self.channelPartnerCloudIdentityInfo, forKey: .channelPartnerCloudIdentityInfo)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ChannelPartnerLink"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
