// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [CloudChannelService.CheckCloudIdentityAccountsExist][google.cloud.channel.v1.CloudChannelService.CheckCloudIdentityAccountsExist].
///
/// [google.cloud.channel.v1.CloudChannelService.CheckCloudIdentityAccountsExist]: <doc:CloudChannelServiceClient/checkCloudIdentityAccountsExist(request:options:)>
public struct CheckCloudIdentityAccountsExistRequest: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Required. The reseller account's resource name.
  /// Parent uses the format: accounts/{account_id}
  public var parent: Swift.String = Swift.String()

  /// Required. Domain to fetch for Cloud Identity account customers, including
  /// domain and team customers. For team customers, please use the domain for
  /// their emails.
  public var domain: Swift.String = Swift.String()

  /// Optional. Primary admin email to fetch for Cloud Identity account team
  /// customer.
  public var primaryAdminEmail: Swift.String = Swift.String()

  /// Initialize a new instance of `CheckCloudIdentityAccountsExistRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CheckCloudIdentityAccountsExistRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.CheckCloudIdentityAccountsExistRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
