// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Cloud Identity information for the Cloud Channel Customer.
public struct CloudIdentityInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// CustomerType indicates verification type needed for using services.
  public var customerType: CloudIdentityInfo.CustomerType = CloudIdentityInfo.CustomerType()

  /// Output only. The primary domain name.
  public var primaryDomain: Swift.String = Swift.String()

  /// Output only. Whether the domain is verified.
  /// This field is not returned for a Customer's cloud_identity_info resource.
  /// Partners can use the domains.get() method of the Workspace SDK's
  /// Directory API, or listen to the PRIMARY_DOMAIN_VERIFIED Pub/Sub event in
  /// to track domain verification of their resolve Workspace customers.
  public var isDomainVerified: Swift.Bool = Swift.Bool()

  /// The alternate email.
  public var alternateEmail: Swift.String = Swift.String()

  /// Phone number associated with the Cloud Identity.
  public var phoneNumber: Swift.String = Swift.String()

  /// Language code.
  public var languageCode: Swift.String = Swift.String()

  /// Output only. URI of Customer's Admin console dashboard.
  public var adminConsoleUri: Swift.String = Swift.String()

  /// Edu information about the customer.
  public var eduData: EduData? = nil

  /// Initialize a new instance of `CloudIdentityInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudIdentityInfo().with { $0.customerType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// CustomerType of the customer
  public enum CustomerType: Codable, Equatable, Sendable {
    /// Not used.
    case unspecified
    /// Domain-owning customer which needs domain verification to use services.
    case domain
    /// Team customer which needs email verification to use services.
    case team
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .domain: return 1
      case .team: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CUSTOMER_TYPE_UNSPECIFIED"
      case .domain: return "DOMAIN"
      case .team: return "TEAM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CustomerType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CUSTOMER_TYPE_UNSPECIFIED": self = .unspecified
      case "DOMAIN": self = .domain
      case "TEAM": self = .team
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CustomerType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .domain
      case 2: self = .team
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .domain: return try container.encode(1)
      case .team: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.CloudIdentityInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
