// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class CloudChannelServiceLogging: CloudChannelServiceStub {
    let inner: any CloudChannelServiceStub
    let logger: Logger

    public init(_ inner: any CloudChannelServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-channel-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudchannel"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CloudChannelService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listCustomers(
      request: ListCustomersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListCustomersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCustomers",
        action: {
          (r: ListCustomersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListCustomersResponse
          in
          return try await self.inner.listCustomers(request: r, options: o)
        })
    }

    public func getCustomer(
      request: GetCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.Customer {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCustomer",
        action: {
          (r: GetCustomerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.Customer
          in
          return try await self.inner.getCustomer(request: r, options: o)
        })
    }

    public func checkCloudIdentityAccountsExist(
      request: CheckCloudIdentityAccountsExistRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.CheckCloudIdentityAccountsExistResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "checkCloudIdentityAccountsExist",
        action: {
          (r: CheckCloudIdentityAccountsExistRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.CheckCloudIdentityAccountsExistResponse
          in
          return try await self.inner.checkCloudIdentityAccountsExist(request: r, options: o)
        })
    }

    public func createCustomer(
      request: CreateCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.Customer {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCustomer",
        action: {
          (r: CreateCustomerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.Customer
          in
          return try await self.inner.createCustomer(request: r, options: o)
        })
    }

    public func updateCustomer(
      request: UpdateCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.Customer {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCustomer",
        action: {
          (r: UpdateCustomerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.Customer
          in
          return try await self.inner.updateCustomer(request: r, options: o)
        })
    }

    public func deleteCustomer(
      request: DeleteCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCustomer",
        action: {
          (r: DeleteCustomerRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteCustomer(request: r, options: o)
        })
    }

    public func importCustomer(
      request: ImportCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.Customer {
      try await self._intercept(
        request: request,
        options: options,
        name: "importCustomer",
        action: {
          (r: ImportCustomerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.Customer
          in
          return try await self.inner.importCustomer(request: r, options: o)
        })
    }

    public func provisionCloudIdentity(
      request: ProvisionCloudIdentityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "provisionCloudIdentity",
        action: {
          (r: ProvisionCloudIdentityRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.provisionCloudIdentity(request: r, options: o)
        })
    }

    public func listEntitlements(
      request: ListEntitlementsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListEntitlementsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEntitlements",
        action: {
          (r: ListEntitlementsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListEntitlementsResponse
          in
          return try await self.inner.listEntitlements(request: r, options: o)
        })
    }

    public func listTransferableSkus(
      request: ListTransferableSkusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListTransferableSkusResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTransferableSkus",
        action: {
          (r: ListTransferableSkusRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListTransferableSkusResponse
          in
          return try await self.inner.listTransferableSkus(request: r, options: o)
        })
    }

    public func listTransferableOffers(
      request: ListTransferableOffersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListTransferableOffersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTransferableOffers",
        action: {
          (r: ListTransferableOffersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListTransferableOffersResponse
          in
          return try await self.inner.listTransferableOffers(request: r, options: o)
        })
    }

    public func getEntitlement(
      request: GetEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.Entitlement {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEntitlement",
        action: {
          (r: GetEntitlementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.Entitlement
          in
          return try await self.inner.getEntitlement(request: r, options: o)
        })
    }

    public func createEntitlement(
      request: CreateEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createEntitlement",
        action: {
          (r: CreateEntitlementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createEntitlement(request: r, options: o)
        })
    }

    public func changeParameters(
      request: ChangeParametersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "changeParameters",
        action: {
          (r: ChangeParametersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.changeParameters(request: r, options: o)
        })
    }

    public func changeRenewalSettings(
      request: ChangeRenewalSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "changeRenewalSettings",
        action: {
          (r: ChangeRenewalSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.changeRenewalSettings(request: r, options: o)
        })
    }

    public func changeOffer(
      request: ChangeOfferRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "changeOffer",
        action: {
          (r: ChangeOfferRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.changeOffer(request: r, options: o)
        })
    }

    public func startPaidService(
      request: StartPaidServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "startPaidService",
        action: {
          (r: StartPaidServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.startPaidService(request: r, options: o)
        })
    }

    public func suspendEntitlement(
      request: SuspendEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "suspendEntitlement",
        action: {
          (r: SuspendEntitlementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.suspendEntitlement(request: r, options: o)
        })
    }

    public func cancelEntitlement(
      request: CancelEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelEntitlement",
        action: {
          (r: CancelEntitlementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.cancelEntitlement(request: r, options: o)
        })
    }

    public func activateEntitlement(
      request: ActivateEntitlementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "activateEntitlement",
        action: {
          (r: ActivateEntitlementRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.activateEntitlement(request: r, options: o)
        })
    }

    public func transferEntitlements(
      request: TransferEntitlementsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "transferEntitlements",
        action: {
          (r: TransferEntitlementsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.transferEntitlements(request: r, options: o)
        })
    }

    public func transferEntitlementsToGoogle(
      request: TransferEntitlementsToGoogleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "transferEntitlementsToGoogle",
        action: {
          (r: TransferEntitlementsToGoogleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.transferEntitlementsToGoogle(request: r, options: o)
        })
    }

    public func listChannelPartnerLinks(
      request: ListChannelPartnerLinksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListChannelPartnerLinksResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listChannelPartnerLinks",
        action: {
          (r: ListChannelPartnerLinksRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListChannelPartnerLinksResponse
          in
          return try await self.inner.listChannelPartnerLinks(request: r, options: o)
        })
    }

    public func getChannelPartnerLink(
      request: GetChannelPartnerLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ChannelPartnerLink {
      try await self._intercept(
        request: request,
        options: options,
        name: "getChannelPartnerLink",
        action: {
          (r: GetChannelPartnerLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ChannelPartnerLink
          in
          return try await self.inner.getChannelPartnerLink(request: r, options: o)
        })
    }

    public func createChannelPartnerLink(
      request: CreateChannelPartnerLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ChannelPartnerLink {
      try await self._intercept(
        request: request,
        options: options,
        name: "createChannelPartnerLink",
        action: {
          (r: CreateChannelPartnerLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ChannelPartnerLink
          in
          return try await self.inner.createChannelPartnerLink(request: r, options: o)
        })
    }

    public func updateChannelPartnerLink(
      request: UpdateChannelPartnerLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ChannelPartnerLink {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateChannelPartnerLink",
        action: {
          (r: UpdateChannelPartnerLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ChannelPartnerLink
          in
          return try await self.inner.updateChannelPartnerLink(request: r, options: o)
        })
    }

    public func getCustomerRepricingConfig(
      request: GetCustomerRepricingConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.CustomerRepricingConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCustomerRepricingConfig",
        action: {
          (r: GetCustomerRepricingConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.CustomerRepricingConfig
          in
          return try await self.inner.getCustomerRepricingConfig(request: r, options: o)
        })
    }

    public func listCustomerRepricingConfigs(
      request: ListCustomerRepricingConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListCustomerRepricingConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCustomerRepricingConfigs",
        action: {
          (r: ListCustomerRepricingConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListCustomerRepricingConfigsResponse
          in
          return try await self.inner.listCustomerRepricingConfigs(request: r, options: o)
        })
    }

    public func createCustomerRepricingConfig(
      request: CreateCustomerRepricingConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.CustomerRepricingConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCustomerRepricingConfig",
        action: {
          (r: CreateCustomerRepricingConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.CustomerRepricingConfig
          in
          return try await self.inner.createCustomerRepricingConfig(request: r, options: o)
        })
    }

    public func updateCustomerRepricingConfig(
      request: UpdateCustomerRepricingConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.CustomerRepricingConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCustomerRepricingConfig",
        action: {
          (r: UpdateCustomerRepricingConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.CustomerRepricingConfig
          in
          return try await self.inner.updateCustomerRepricingConfig(request: r, options: o)
        })
    }

    public func deleteCustomerRepricingConfig(
      request: DeleteCustomerRepricingConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCustomerRepricingConfig",
        action: {
          (r: DeleteCustomerRepricingConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteCustomerRepricingConfig(request: r, options: o)
        })
    }

    public func getChannelPartnerRepricingConfig(
      request: GetChannelPartnerRepricingConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ChannelPartnerRepricingConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getChannelPartnerRepricingConfig",
        action: {
          (r: GetChannelPartnerRepricingConfigRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudChannelV1.ChannelPartnerRepricingConfig
          in
          return try await self.inner.getChannelPartnerRepricingConfig(request: r, options: o)
        })
    }

    public func listChannelPartnerRepricingConfigs(
      request: ListChannelPartnerRepricingConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListChannelPartnerRepricingConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listChannelPartnerRepricingConfigs",
        action: {
          (r: ListChannelPartnerRepricingConfigsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudChannelV1.ListChannelPartnerRepricingConfigsResponse
          in
          return try await self.inner.listChannelPartnerRepricingConfigs(request: r, options: o)
        })
    }

    public func createChannelPartnerRepricingConfig(
      request: CreateChannelPartnerRepricingConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ChannelPartnerRepricingConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "createChannelPartnerRepricingConfig",
        action: {
          (r: CreateChannelPartnerRepricingConfigRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudChannelV1.ChannelPartnerRepricingConfig
          in
          return try await self.inner.createChannelPartnerRepricingConfig(request: r, options: o)
        })
    }

    public func updateChannelPartnerRepricingConfig(
      request: UpdateChannelPartnerRepricingConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ChannelPartnerRepricingConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateChannelPartnerRepricingConfig",
        action: {
          (r: UpdateChannelPartnerRepricingConfigRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudChannelV1.ChannelPartnerRepricingConfig
          in
          return try await self.inner.updateChannelPartnerRepricingConfig(request: r, options: o)
        })
    }

    public func deleteChannelPartnerRepricingConfig(
      request: DeleteChannelPartnerRepricingConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteChannelPartnerRepricingConfig",
        action: {
          (r: DeleteChannelPartnerRepricingConfigRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteChannelPartnerRepricingConfig(request: r, options: o)
        })
    }

    public func listSkuGroups(
      request: ListSkuGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListSkuGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSkuGroups",
        action: {
          (r: ListSkuGroupsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListSkuGroupsResponse
          in
          return try await self.inner.listSkuGroups(request: r, options: o)
        })
    }

    public func listSkuGroupBillableSkus(
      request: ListSkuGroupBillableSkusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListSkuGroupBillableSkusResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSkuGroupBillableSkus",
        action: {
          (r: ListSkuGroupBillableSkusRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListSkuGroupBillableSkusResponse
          in
          return try await self.inner.listSkuGroupBillableSkus(request: r, options: o)
        })
    }

    public func lookupOffer(
      request: LookupOfferRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.Offer {
      try await self._intercept(
        request: request,
        options: options,
        name: "lookupOffer",
        action: {
          (r: LookupOfferRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.Offer
          in
          return try await self.inner.lookupOffer(request: r, options: o)
        })
    }

    public func listProducts(
      request: ListProductsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListProductsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listProducts",
        action: {
          (r: ListProductsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListProductsResponse
          in
          return try await self.inner.listProducts(request: r, options: o)
        })
    }

    public func listSkus(
      request: ListSkusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListSkusResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSkus",
        action: {
          (r: ListSkusRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListSkusResponse
          in
          return try await self.inner.listSkus(request: r, options: o)
        })
    }

    public func listOffers(
      request: ListOffersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListOffersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOffers",
        action: {
          (r: ListOffersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListOffersResponse
          in
          return try await self.inner.listOffers(request: r, options: o)
        })
    }

    public func listPurchasableSkus(
      request: ListPurchasableSkusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListPurchasableSkusResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPurchasableSkus",
        action: {
          (r: ListPurchasableSkusRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListPurchasableSkusResponse
          in
          return try await self.inner.listPurchasableSkus(request: r, options: o)
        })
    }

    public func listPurchasableOffers(
      request: ListPurchasableOffersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListPurchasableOffersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPurchasableOffers",
        action: {
          (r: ListPurchasableOffersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListPurchasableOffersResponse
          in
          return try await self.inner.listPurchasableOffers(request: r, options: o)
        })
    }

    public func queryEligibleBillingAccounts(
      request: QueryEligibleBillingAccountsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.QueryEligibleBillingAccountsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "queryEligibleBillingAccounts",
        action: {
          (r: QueryEligibleBillingAccountsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.QueryEligibleBillingAccountsResponse
          in
          return try await self.inner.queryEligibleBillingAccounts(request: r, options: o)
        })
    }

    public func registerSubscriber(
      request: RegisterSubscriberRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.RegisterSubscriberResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "registerSubscriber",
        action: {
          (r: RegisterSubscriberRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.RegisterSubscriberResponse
          in
          return try await self.inner.registerSubscriber(request: r, options: o)
        })
    }

    public func unregisterSubscriber(
      request: UnregisterSubscriberRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.UnregisterSubscriberResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "unregisterSubscriber",
        action: {
          (r: UnregisterSubscriberRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.UnregisterSubscriberResponse
          in
          return try await self.inner.unregisterSubscriber(request: r, options: o)
        })
    }

    public func listSubscribers(
      request: ListSubscribersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListSubscribersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSubscribers",
        action: {
          (r: ListSubscribersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListSubscribersResponse
          in
          return try await self.inner.listSubscribers(request: r, options: o)
        })
    }

    public func listEntitlementChanges(
      request: ListEntitlementChangesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudChannelV1.ListEntitlementChangesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEntitlementChanges",
        action: {
          (r: ListEntitlementChangesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudChannelV1.ListEntitlementChangesResponse
          in
          return try await self.inner.listEntitlementChanges(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
