// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Entity representing a Cloud Identity account that may be
/// associated with a Channel Services API partner.
public struct CloudIdentityCustomerAccount: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Returns true if a Cloud Identity account exists for a specific domain.
  public var existing: Swift.Bool = Swift.Bool()

  /// Returns true if the Cloud Identity account is associated with a customer
  /// of the Channel Services partner (with active subscriptions or purchase
  /// consents).
  public var owned: Swift.Bool = Swift.Bool()

  /// If owned = true, the name of the customer that owns the Cloud Identity
  /// account.
  /// Customer_name uses the format:
  /// accounts/{account_id}/customers/{customer_id}
  public var customerName: Swift.String = Swift.String()

  /// If existing = true, the Cloud Identity ID of the customer.
  public var customerCloudIdentityId: Swift.String = Swift.String()

  /// If existing = true, the type of the customer.
  public var customerType: CloudIdentityInfo.CustomerType = CloudIdentityInfo.CustomerType()

  /// If existing = true, and is 2-tier customer, the channel partner of the
  /// customer.
  public var channelPartnerCloudIdentityId: Swift.String = Swift.String()

  /// Initialize a new instance of `CloudIdentityCustomerAccount`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudIdentityCustomerAccount().with { $0.existing = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.CloudIdentityCustomerAccount"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
