// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The definition of a report column. Specifies the data properties
/// in the corresponding position of the report rows.
@available(*, deprecated)
public struct Column: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The unique name of the column (for example, customer_domain,
  /// channel_partner, customer_cost). You can use column IDs in
  /// [RunReportJobRequest.filter][google.cloud.channel.v1.RunReportJobRequest.filter].
  /// To see all reports and their columns, call
  /// [CloudChannelReportsService.ListReports][google.cloud.channel.v1.CloudChannelReportsService.ListReports].
  ///
  /// [google.cloud.channel.v1.CloudChannelReportsService.ListReports]: <doc:CloudChannelReportsServiceClient/listReports(request:)>
  /// [google.cloud.channel.v1.RunReportJobRequest.filter]: <doc:RunReportJobRequest/filter>
  public var columnId: Swift.String = Swift.String()

  /// The column's display name.
  public var displayName: Swift.String = Swift.String()

  /// The type of the values for this column.
  public var dataType: Column.DataType = Column.DataType()

  /// Initialize a new instance of `Column`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Column().with { $0.columnId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Available data types for columns. Corresponds to the fields in the
  /// ReportValue `oneof` field.
  public enum DataType: Codable, Equatable, Sendable {
    /// Not used.
    case unspecified
    /// ReportValues for this column will use string_value.
    case string
    /// ReportValues for this column will use int_value.
    case int
    /// ReportValues for this column will use decimal_value.
    case decimal
    /// ReportValues for this column will use money_value.
    case money
    /// ReportValues for this column will use date_value.
    case date
    /// ReportValues for this column will use date_time_value.
    case dateTime
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .string: return 1
      case .int: return 2
      case .decimal: return 3
      case .money: return 4
      case .date: return 5
      case .dateTime: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DATA_TYPE_UNSPECIFIED"
      case .string: return "STRING"
      case .int: return "INT"
      case .decimal: return "DECIMAL"
      case .money: return "MONEY"
      case .date: return "DATE"
      case .dateTime: return "DATE_TIME"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DataType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DATA_TYPE_UNSPECIFIED": self = .unspecified
      case "STRING": self = .string
      case "INT": self = .int
      case "DECIMAL": self = .decimal
      case "MONEY": self = .money
      case "DATE": self = .date
      case "DATE_TIME": self = .dateTime
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DataType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .string
      case 2: self = .int
      case 3: self = .decimal
      case 4: self = .money
      case 5: self = .date
      case 6: self = .dateTime
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .string: return try container.encode(1)
      case .int: return try container.encode(2)
      case .decimal: return try container.encode(3)
      case .money: return try container.encode(4)
      case .date: return try container.encode(5)
      case .dateTime: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.Column"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
