// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Specifies the override to conditionally apply.
public struct ConditionalOverride: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Information about the applied override's adjustment.
  public var adjustment: RepricingAdjustment? = nil

  /// Required. The [RebillingBasis][google.cloud.channel.v1.RebillingBasis] to
  /// use for the applied override. Shows the relative cost based on your
  /// repricing costs.
  ///
  /// [google.cloud.channel.v1.RebillingBasis]: <doc:RebillingBasis>
  public var rebillingBasis: RebillingBasis = RebillingBasis()

  /// Required. Specifies the condition which, if met, will apply the override.
  public var repricingCondition: RepricingCondition? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConditionalOverride`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConditionalOverride().with { $0.adjustment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let adjustment = CodingKeys(stringValue: "adjustment")
    static let rebillingBasis = CodingKeys(stringValue: "rebillingBasis")
    static let repricingCondition = CodingKeys(stringValue: "repricingCondition")

    static let _knownKeys: Set<Swift.String> = [
      "adjustment",
      "rebillingBasis",
      "repricingCondition",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.adjustment = try container.decodeIfPresent(RepricingAdjustment.self, forKey: .adjustment)
    if let value = try container.decodeIfPresent(RebillingBasis.self, forKey: .rebillingBasis) {
      self.rebillingBasis = value
    }
    self.repricingCondition = try container.decodeIfPresent(
      RepricingCondition.self, forKey: .repricingCondition)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.adjustment, forKey: .adjustment)
    try container.encode(self.rebillingBasis, forKey: .rebillingBasis)
    try container.encodeIfPresent(self.repricingCondition, forKey: .repricingCondition)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ConditionalOverride"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
