// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Contact information for a customer account.
public struct ContactInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The customer account contact's first name. Optional for Team customers.
  public var firstName: Swift.String = Swift.String()

  /// The customer account contact's last name. Optional for Team customers.
  public var lastName: Swift.String = Swift.String()

  /// Output only. The customer account contact's display name, formatted as a
  /// combination of the customer's first and last name.
  public var displayName: Swift.String = Swift.String()

  /// The customer account's contact email. Required for entitlements that create
  /// admin.google.com accounts, and serves as the customer's username for those
  /// accounts. Use this email to invite Team customers.
  public var email: Swift.String = Swift.String()

  /// Optional. The customer account contact's job title.
  public var title: Swift.String = Swift.String()

  /// The customer account's contact phone number.
  public var phone: Swift.String = Swift.String()

  /// Initialize a new instance of `ContactInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ContactInfo().with { $0.firstName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ContactInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
