// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Entity representing a customer of a reseller or distributor.
public struct Customer: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the customer.
  /// Format: accounts/{account_id}/customers/{customer_id}
  public var name: Swift.String = Swift.String()

  /// Required. Name of the organization that the customer entity represents.
  public var orgDisplayName: Swift.String = Swift.String()

  /// Required. The organization address for the customer. To enforce US laws and
  /// embargoes, we require a region, postal code, and address lines. You must
  /// provide valid addresses for every customer. To set the customer's
  /// language, use the Customer-level language code.
  public var orgPostalAddress: GoogleType.PostalAddress? = nil

  /// Primary contact info.
  public var primaryContactInfo: ContactInfo? = nil

  /// Secondary contact email. You need to provide an alternate email to create
  /// different domains if a primary contact email already exists. Users will
  /// receive a notification with credentials when you create an admin.google.com
  /// account. Secondary emails are also recovery email addresses. Alternate
  /// emails are optional when you create Team customers.
  public var alternateEmail: Swift.String = Swift.String()

  /// Required. The customer's primary domain. Must match the primary contact
  /// email's domain.
  public var domain: Swift.String = Swift.String()

  /// Output only. Time when the customer was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. Time when the customer was updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. The customer's Cloud Identity ID if the customer has a Cloud
  /// Identity resource.
  public var cloudIdentityId: Swift.String = Swift.String()

  /// Optional. The BCP-47 language code, such as "en-US" or "sr-Latn". For more
  /// information, see
  /// https://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
  public var languageCode: Swift.String = Swift.String()

  /// Output only. Cloud Identity information for the customer.
  /// Populated only if a Cloud Identity account exists for this customer.
  public var cloudIdentityInfo: CloudIdentityInfo? = nil

  /// Cloud Identity ID of the customer's channel partner.
  /// Populated only if a channel partner exists for this customer.
  public var channelPartnerId: Swift.String = Swift.String()

  /// Optional. External CRM ID for the customer.
  /// Populated only if a CRM ID exists for this customer.
  public var correlationId: Swift.String = Swift.String()

  /// Optional. Indicate if a customer is attesting about the correctness of
  /// provided information. Only required if creating a GCP Entitlement.
  public var customerAttestationState: Customer.CustomerAttestationState =
    Customer.CustomerAttestationState()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Customer`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Customer().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let orgDisplayName = CodingKeys(stringValue: "orgDisplayName")
    static let orgPostalAddress = CodingKeys(stringValue: "orgPostalAddress")
    static let primaryContactInfo = CodingKeys(stringValue: "primaryContactInfo")
    static let alternateEmail = CodingKeys(stringValue: "alternateEmail")
    static let domain = CodingKeys(stringValue: "domain")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let cloudIdentityId = CodingKeys(stringValue: "cloudIdentityId")
    static let languageCode = CodingKeys(stringValue: "languageCode")
    static let cloudIdentityInfo = CodingKeys(stringValue: "cloudIdentityInfo")
    static let channelPartnerId = CodingKeys(stringValue: "channelPartnerId")
    static let correlationId = CodingKeys(stringValue: "correlationId")
    static let customerAttestationState = CodingKeys(stringValue: "customerAttestationState")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "orgDisplayName",
      "orgPostalAddress",
      "primaryContactInfo",
      "alternateEmail",
      "domain",
      "createTime",
      "updateTime",
      "cloudIdentityId",
      "languageCode",
      "cloudIdentityInfo",
      "channelPartnerId",
      "correlationId",
      "customerAttestationState",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orgDisplayName) {
      self.orgDisplayName = value
    }
    self.orgPostalAddress = try container.decodeIfPresent(
      GoogleType.PostalAddress.self, forKey: .orgPostalAddress)
    self.primaryContactInfo = try container.decodeIfPresent(
      ContactInfo.self, forKey: .primaryContactInfo)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .alternateEmail) {
      self.alternateEmail = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .domain) {
      self.domain = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cloudIdentityId) {
      self.cloudIdentityId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageCode) {
      self.languageCode = value
    }
    self.cloudIdentityInfo = try container.decodeIfPresent(
      CloudIdentityInfo.self, forKey: .cloudIdentityInfo)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .channelPartnerId) {
      self.channelPartnerId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .correlationId) {
      self.correlationId = value
    }
    if let value = try container.decodeIfPresent(
      Customer.CustomerAttestationState.self, forKey: .customerAttestationState)
    {
      self.customerAttestationState = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.orgDisplayName, forKey: .orgDisplayName)
    try container.encodeIfPresent(self.orgPostalAddress, forKey: .orgPostalAddress)
    try container.encodeIfPresent(self.primaryContactInfo, forKey: .primaryContactInfo)
    try container.encode(self.alternateEmail, forKey: .alternateEmail)
    try container.encode(self.domain, forKey: .domain)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.cloudIdentityId, forKey: .cloudIdentityId)
    try container.encode(self.languageCode, forKey: .languageCode)
    try container.encodeIfPresent(self.cloudIdentityInfo, forKey: .cloudIdentityInfo)
    try container.encode(self.channelPartnerId, forKey: .channelPartnerId)
    try container.encode(self.correlationId, forKey: .correlationId)
    try container.encode(self.customerAttestationState, forKey: .customerAttestationState)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The enum represents if a customer belongs to public sector
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum CustomerAttestationState: Codable, Equatable, Sendable {
    /// Default value if not set yet
    case unspecified
    /// Customer is exempt from attesting based on exemption list at
    /// https://cloud.google.com/terms/direct-tos-exemptions. Contact information
    /// of customer will be mandatory.
    case exempt
    /// Customer is not exempt and has verified the information provided is
    /// correct. Contact information of customer will be mandatory.
    case nonExemptAndInfoVerified
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .exempt: return 1
      case .nonExemptAndInfoVerified: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CUSTOMER_ATTESTATION_STATE_UNSPECIFIED"
      case .exempt: return "EXEMPT"
      case .nonExemptAndInfoVerified: return "NON_EXEMPT_AND_INFO_VERIFIED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CustomerAttestationState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CUSTOMER_ATTESTATION_STATE_UNSPECIFIED": self = .unspecified
      case "EXEMPT": self = .exempt
      case "NON_EXEMPT_AND_INFO_VERIFIED": self = .nonExemptAndInfoVerified
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CustomerAttestationState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .exempt
      case 2: self = .nonExemptAndInfoVerified
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CUSTOMER_ATTESTATION_STATE_UNSPECIFIED")
      case .exempt: return try container.encode("EXEMPT")
      case .nonExemptAndInfoVerified: return try container.encode("NON_EXEMPT_AND_INFO_VERIFIED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.Customer"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
