// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An entitlement is a representation of a customer's ability to use a service.
public struct Entitlement: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Resource name of an entitlement in the form:
  /// accounts/{account_id}/customers/{customer_id}/entitlements/{entitlement_id}.
  public var name: Swift.String = Swift.String()

  /// Output only. The time at which the entitlement is created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time at which the entitlement is updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Required. The offer resource name for which the entitlement is to be
  /// created. Takes the form: accounts/{account_id}/offers/{offer_id}.
  public var offer: Swift.String = Swift.String()

  /// Commitment settings for a commitment-based Offer.
  /// Required for commitment based offers.
  public var commitmentSettings: CommitmentSettings? = nil

  /// Output only. Current provisioning state of the entitlement.
  public var provisioningState: Entitlement.ProvisioningState = Entitlement.ProvisioningState()

  /// Output only. Service provisioning details for the entitlement.
  public var provisionedService: ProvisionedService? = nil

  /// Output only. Enumerable of all current suspension reasons for an
  /// entitlement.
  public var suspensionReasons: [Entitlement.SuspensionReason] = []

  /// Optional. This purchase order (PO) information is for resellers to use for
  /// their company tracking usage. If a purchaseOrderId value is given, it
  /// appears in the API responses and shows up in the invoice. The property
  /// accepts up to 80 plain text characters. This is only supported for Google
  /// Workspace entitlements.
  public var purchaseOrderId: Swift.String = Swift.String()

  /// Output only. Settings for trial offers.
  public var trialSettings: TrialSettings? = nil

  /// Association information to other entitlements.
  public var associationInfo: AssociationInfo? = nil

  /// Extended entitlement parameters. When creating an entitlement, valid
  /// parameter names and values are defined in the
  /// [Offer.parameter_definitions][google.cloud.channel.v1.Offer.parameter_definitions].
  ///
  /// For Google Workspace, the following Parameters may be accepted as input:
  ///
  /// - max_units: The maximum assignable units for a flexible offer
  ///
  /// OR
  ///
  /// - num_units: The total commitment for commitment-based offers
  ///
  /// The response may additionally include the following output-only Parameters:
  ///
  /// - assigned_units: The number of licenses assigned to users.
  ///
  /// For Google Cloud billing subaccounts, the following Parameter may be
  /// accepted as input:
  ///
  /// - display_name: The display name of the billing subaccount.
  ///
  /// [google.cloud.channel.v1.Offer.parameter_definitions]: <doc:Offer/parameterDefinitions>
  public var parameters: [Parameter] = []

  /// Optional. The billing account resource name that is used to pay for this
  /// entitlement.
  public var billingAccount: Swift.String = Swift.String()

  /// Optional. Price reference ID for the offer. Only for offers that require
  /// additional price information. Used to guarantee that the pricing is
  /// consistent between quoting the offer and placing the order.
  public var priceReferenceId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Entitlement`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Entitlement().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let offer = CodingKeys(stringValue: "offer")
    static let commitmentSettings = CodingKeys(stringValue: "commitmentSettings")
    static let provisioningState = CodingKeys(stringValue: "provisioningState")
    static let provisionedService = CodingKeys(stringValue: "provisionedService")
    static let suspensionReasons = CodingKeys(stringValue: "suspensionReasons")
    static let purchaseOrderId = CodingKeys(stringValue: "purchaseOrderId")
    static let trialSettings = CodingKeys(stringValue: "trialSettings")
    static let associationInfo = CodingKeys(stringValue: "associationInfo")
    static let parameters = CodingKeys(stringValue: "parameters")
    static let billingAccount = CodingKeys(stringValue: "billingAccount")
    static let priceReferenceId = CodingKeys(stringValue: "priceReferenceId")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "offer",
      "commitmentSettings",
      "provisioningState",
      "provisionedService",
      "suspensionReasons",
      "purchaseOrderId",
      "trialSettings",
      "associationInfo",
      "parameters",
      "billingAccount",
      "priceReferenceId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .offer) {
      self.offer = value
    }
    self.commitmentSettings = try container.decodeIfPresent(
      CommitmentSettings.self, forKey: .commitmentSettings)
    if let value = try container.decodeIfPresent(
      Entitlement.ProvisioningState.self, forKey: .provisioningState)
    {
      self.provisioningState = value
    }
    self.provisionedService = try container.decodeIfPresent(
      ProvisionedService.self, forKey: .provisionedService)
    if let value = try container.decodeIfPresent(
      [Entitlement.SuspensionReason].self, forKey: .suspensionReasons)
    {
      self.suspensionReasons = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .purchaseOrderId) {
      self.purchaseOrderId = value
    }
    self.trialSettings = try container.decodeIfPresent(TrialSettings.self, forKey: .trialSettings)
    self.associationInfo = try container.decodeIfPresent(
      AssociationInfo.self, forKey: .associationInfo)
    if let value = try container.decodeIfPresent([Parameter].self, forKey: .parameters) {
      self.parameters = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .billingAccount) {
      self.billingAccount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .priceReferenceId) {
      self.priceReferenceId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.offer, forKey: .offer)
    try container.encodeIfPresent(self.commitmentSettings, forKey: .commitmentSettings)
    try container.encode(self.provisioningState, forKey: .provisioningState)
    try container.encodeIfPresent(self.provisionedService, forKey: .provisionedService)
    try container.encode(self.suspensionReasons, forKey: .suspensionReasons)
    try container.encode(self.purchaseOrderId, forKey: .purchaseOrderId)
    try container.encodeIfPresent(self.trialSettings, forKey: .trialSettings)
    try container.encodeIfPresent(self.associationInfo, forKey: .associationInfo)
    try container.encode(self.parameters, forKey: .parameters)
    try container.encode(self.billingAccount, forKey: .billingAccount)
    try container.encode(self.priceReferenceId, forKey: .priceReferenceId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Indicates the current provisioning state of the entitlement.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ProvisioningState: Codable, Equatable, Hashable, Sendable {
    /// Not used.
    case unspecified
    /// The entitlement is currently active.
    case active
    /// The entitlement is currently suspended.
    case suspended
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .suspended: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROVISIONING_STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .suspended: return "SUSPENDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ProvisioningState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROVISIONING_STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "SUSPENDED": self = .suspended
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ProvisioningState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 5: self = .suspended
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PROVISIONING_STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .suspended: return try container.encode("SUSPENDED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Suspension reason for an entitlement if
  /// [provisioning_state][google.cloud.channel.v1.Entitlement.provisioning_state]
  /// = SUSPENDED.
  ///
  /// [google.cloud.channel.v1.Entitlement.provisioning_state]: <doc:Entitlement/provisioningState>
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum SuspensionReason: Codable, Equatable, Hashable, Sendable {
    /// Not used.
    case unspecified
    /// Entitlement was manually suspended by the Reseller.
    case resellerInitiated
    /// Trial ended.
    case trialEnded
    /// Entitlement renewal was canceled.
    case renewalWithTypeCancel
    /// Entitlement was automatically suspended on creation for pending ToS
    /// acceptance on customer.
    case pendingTosAcceptance
    /// Other reasons (internal reasons, abuse, etc.).
    case other
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .resellerInitiated: return 1
      case .trialEnded: return 2
      case .renewalWithTypeCancel: return 3
      case .pendingTosAcceptance: return 4
      case .other: return 100
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SUSPENSION_REASON_UNSPECIFIED"
      case .resellerInitiated: return "RESELLER_INITIATED"
      case .trialEnded: return "TRIAL_ENDED"
      case .renewalWithTypeCancel: return "RENEWAL_WITH_TYPE_CANCEL"
      case .pendingTosAcceptance: return "PENDING_TOS_ACCEPTANCE"
      case .other: return "OTHER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SuspensionReason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SUSPENSION_REASON_UNSPECIFIED": self = .unspecified
      case "RESELLER_INITIATED": self = .resellerInitiated
      case "TRIAL_ENDED": self = .trialEnded
      case "RENEWAL_WITH_TYPE_CANCEL": self = .renewalWithTypeCancel
      case "PENDING_TOS_ACCEPTANCE": self = .pendingTosAcceptance
      case "OTHER": self = .other
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SuspensionReason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .resellerInitiated
      case 2: self = .trialEnded
      case 3: self = .renewalWithTypeCancel
      case 4: self = .pendingTosAcceptance
      case 100: self = .other
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SUSPENSION_REASON_UNSPECIFIED")
      case .resellerInitiated: return try container.encode("RESELLER_INITIATED")
      case .trialEnded: return try container.encode("TRIAL_ENDED")
      case .renewalWithTypeCancel: return try container.encode("RENEWAL_WITH_TYPE_CANCEL")
      case .pendingTosAcceptance: return try container.encode("PENDING_TOS_ACCEPTANCE")
      case .other: return try container.encode("OTHER")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.Entitlement"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
