// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Change event entry for Entitlement order history
public struct EntitlementChange: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Resource name of an entitlement in the form:
  /// accounts/{account_id}/customers/{customer_id}/entitlements/{entitlement_id}
  public var entitlement: Swift.String = Swift.String()

  /// Required. Resource name of the Offer at the time of change.
  /// Takes the form: accounts/{account_id}/offers/{offer_id}.
  public var offer: Swift.String = Swift.String()

  /// Service provisioned for an Entitlement.
  public var provisionedService: ProvisionedService? = nil

  /// The change action type.
  public var changeType: EntitlementChange.ChangeType = EntitlementChange.ChangeType()

  /// The submitted time of the change.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Operator type responsible for the change.
  public var operatorType: EntitlementChange.OperatorType = EntitlementChange.OperatorType()

  /// Extended parameters, such as:
  /// purchase_order_number, gcp_details;
  /// internal_correlation_id, long_running_operation_id, order_id;
  /// etc.
  public var parameters: [Parameter] = []

  /// Human-readable identifier that shows what operator made a change.
  /// When the operator_type is RESELLER, this is the user's email address.
  /// For all other operator types, this is empty.
  public var `operator`: Swift.String = Swift.String()

  /// The reason the change was made
  public var changeReason: OneOf_ChangeReason? = nil

  /// Initialize a new instance of `EntitlementChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EntitlementChange().with { $0.suspensionReason = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case suspensionReason = "suspensionReason"
    case cancellationReason = "cancellationReason"
    case activationReason = "activationReason"
    case otherChangeReason = "otherChangeReason"
    case entitlement = "entitlement"
    case offer = "offer"
    case provisionedService = "provisionedService"
    case changeType = "changeType"
    case createTime = "createTime"
    case operatorType = "operatorType"
    case parameters = "parameters"
    case `operator` = "operator"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.entitlement = try container.decode(Swift.String.self, forKey: .entitlement)
    self.offer = try container.decode(Swift.String.self, forKey: .offer)
    self.provisionedService = try container.decodeIfPresent(
      ProvisionedService.self, forKey: .provisionedService)
    self.changeType = try container.decode(EntitlementChange.ChangeType.self, forKey: .changeType)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.operatorType = try container.decode(
      EntitlementChange.OperatorType.self, forKey: .operatorType)
    self.parameters = try container.decode([Parameter].self, forKey: .parameters)
    self.`operator` = try container.decode(Swift.String.self, forKey: .`operator`)

    var changeReason: OneOf_ChangeReason? = nil
    let changeReasonCheckAndSet = {
      if changeReason != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'changeReason'"))
      }
      changeReason = $0
    }
    if let suspensionReason = try container.decodeIfPresent(
      Entitlement.SuspensionReason.self, forKey: .suspensionReason)
    {
      try changeReasonCheckAndSet(.suspensionReason(suspensionReason))
    }
    if let cancellationReason = try container.decodeIfPresent(
      EntitlementChange.CancellationReason.self, forKey: .cancellationReason)
    {
      try changeReasonCheckAndSet(.cancellationReason(cancellationReason))
    }
    if let activationReason = try container.decodeIfPresent(
      EntitlementChange.ActivationReason.self, forKey: .activationReason)
    {
      try changeReasonCheckAndSet(.activationReason(activationReason))
    }
    if let otherChangeReason = try container.decodeIfPresent(
      Swift.String.self, forKey: .otherChangeReason)
    {
      try changeReasonCheckAndSet(.otherChangeReason(otherChangeReason))
    }
    self.changeReason = changeReason
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.entitlement, forKey: .entitlement)
    try container.encode(self.offer, forKey: .offer)
    try container.encode(self.provisionedService, forKey: .provisionedService)
    try container.encode(self.changeType, forKey: .changeType)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.operatorType, forKey: .operatorType)
    try container.encode(self.parameters, forKey: .parameters)
    try container.encode(self.`operator`, forKey: .`operator`)

    if let choice = self.changeReason {
      switch choice {
      case .suspensionReason(let value):
        try container.encode(value, forKey: .suspensionReason)
      case .cancellationReason(let value):
        try container.encode(value, forKey: .cancellationReason)
      case .activationReason(let value):
        try container.encode(value, forKey: .activationReason)
      case .otherChangeReason(let value):
        try container.encode(value, forKey: .otherChangeReason)
      }
    }
  }

  /// Specifies the type of change action
  public enum ChangeType: Codable, Equatable, Sendable {
    /// Not used.
    case unspecified
    /// New Entitlement was created.
    case created
    /// Price plan associated with an Entitlement was changed.
    case pricePlanSwitched
    /// Number of seats committed for a commitment Entitlement was changed.
    case commitmentChanged
    /// An annual Entitlement was renewed.
    case renewed
    /// Entitlement was suspended.
    case suspended
    /// Entitlement was activated.
    case activated
    /// Entitlement was cancelled.
    case cancelled
    /// Entitlement was upgraded or downgraded for ex. from Google Workspace
    /// Business Standard to Google Workspace Business Plus.
    case skuChanged
    /// The settings for renewal of an Entitlement have changed.
    case renewalSettingChanged
    /// Use for Google Workspace subscription.
    /// Either a trial was converted to a paid subscription or a new subscription
    /// with no trial is created.
    case paidSubscriptionStarted
    /// License cap was changed for the entitlement.
    case licenseCapChanged
    /// The suspension details have changed (but it is still suspended).
    case suspensionDetailsChanged
    /// The trial end date was extended.
    case trialEndDateExtended
    /// Entitlement started trial.
    case trialStarted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .created: return 1
      case .pricePlanSwitched: return 3
      case .commitmentChanged: return 4
      case .renewed: return 5
      case .suspended: return 6
      case .activated: return 7
      case .cancelled: return 8
      case .skuChanged: return 9
      case .renewalSettingChanged: return 10
      case .paidSubscriptionStarted: return 11
      case .licenseCapChanged: return 12
      case .suspensionDetailsChanged: return 13
      case .trialEndDateExtended: return 14
      case .trialStarted: return 15
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CHANGE_TYPE_UNSPECIFIED"
      case .created: return "CREATED"
      case .pricePlanSwitched: return "PRICE_PLAN_SWITCHED"
      case .commitmentChanged: return "COMMITMENT_CHANGED"
      case .renewed: return "RENEWED"
      case .suspended: return "SUSPENDED"
      case .activated: return "ACTIVATED"
      case .cancelled: return "CANCELLED"
      case .skuChanged: return "SKU_CHANGED"
      case .renewalSettingChanged: return "RENEWAL_SETTING_CHANGED"
      case .paidSubscriptionStarted: return "PAID_SUBSCRIPTION_STARTED"
      case .licenseCapChanged: return "LICENSE_CAP_CHANGED"
      case .suspensionDetailsChanged: return "SUSPENSION_DETAILS_CHANGED"
      case .trialEndDateExtended: return "TRIAL_END_DATE_EXTENDED"
      case .trialStarted: return "TRIAL_STARTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ChangeType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CHANGE_TYPE_UNSPECIFIED": self = .unspecified
      case "CREATED": self = .created
      case "PRICE_PLAN_SWITCHED": self = .pricePlanSwitched
      case "COMMITMENT_CHANGED": self = .commitmentChanged
      case "RENEWED": self = .renewed
      case "SUSPENDED": self = .suspended
      case "ACTIVATED": self = .activated
      case "CANCELLED": self = .cancelled
      case "SKU_CHANGED": self = .skuChanged
      case "RENEWAL_SETTING_CHANGED": self = .renewalSettingChanged
      case "PAID_SUBSCRIPTION_STARTED": self = .paidSubscriptionStarted
      case "LICENSE_CAP_CHANGED": self = .licenseCapChanged
      case "SUSPENSION_DETAILS_CHANGED": self = .suspensionDetailsChanged
      case "TRIAL_END_DATE_EXTENDED": self = .trialEndDateExtended
      case "TRIAL_STARTED": self = .trialStarted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ChangeType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .created
      case 3: self = .pricePlanSwitched
      case 4: self = .commitmentChanged
      case 5: self = .renewed
      case 6: self = .suspended
      case 7: self = .activated
      case 8: self = .cancelled
      case 9: self = .skuChanged
      case 10: self = .renewalSettingChanged
      case 11: self = .paidSubscriptionStarted
      case 12: self = .licenseCapChanged
      case 13: self = .suspensionDetailsChanged
      case 14: self = .trialEndDateExtended
      case 15: self = .trialStarted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .created: return try container.encode(1)
      case .pricePlanSwitched: return try container.encode(3)
      case .commitmentChanged: return try container.encode(4)
      case .renewed: return try container.encode(5)
      case .suspended: return try container.encode(6)
      case .activated: return try container.encode(7)
      case .cancelled: return try container.encode(8)
      case .skuChanged: return try container.encode(9)
      case .renewalSettingChanged: return try container.encode(10)
      case .paidSubscriptionStarted: return try container.encode(11)
      case .licenseCapChanged: return try container.encode(12)
      case .suspensionDetailsChanged: return try container.encode(13)
      case .trialEndDateExtended: return try container.encode(14)
      case .trialStarted: return try container.encode(15)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Specifies the type of operator responsible for the change
  public enum OperatorType: Codable, Equatable, Sendable {
    /// Not used.
    case unspecified
    /// Customer service representative.
    case customerServiceRepresentative
    /// System auto job.
    case system
    /// Customer user.
    case customer
    /// Reseller user.
    case reseller
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .customerServiceRepresentative: return 1
      case .system: return 2
      case .customer: return 3
      case .reseller: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OPERATOR_TYPE_UNSPECIFIED"
      case .customerServiceRepresentative: return "CUSTOMER_SERVICE_REPRESENTATIVE"
      case .system: return "SYSTEM"
      case .customer: return "CUSTOMER"
      case .reseller: return "RESELLER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OperatorType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OPERATOR_TYPE_UNSPECIFIED": self = .unspecified
      case "CUSTOMER_SERVICE_REPRESENTATIVE": self = .customerServiceRepresentative
      case "SYSTEM": self = .system
      case "CUSTOMER": self = .customer
      case "RESELLER": self = .reseller
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OperatorType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .customerServiceRepresentative
      case 2: self = .system
      case 3: self = .customer
      case 4: self = .reseller
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .customerServiceRepresentative: return try container.encode(1)
      case .system: return try container.encode(2)
      case .customer: return try container.encode(3)
      case .reseller: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Cancellation reason for the entitlement
  public enum CancellationReason: Codable, Equatable, Sendable {
    /// Not used.
    case unspecified
    /// Reseller triggered a cancellation of the service.
    case serviceTerminated
    /// Relationship between the reseller and customer has ended due to a
    /// transfer.
    case relationshipEnded
    /// Entitlement transferred away from reseller while still keeping other
    /// entitlement(s) with the reseller.
    case partialTransfer
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .serviceTerminated: return 1
      case .relationshipEnded: return 2
      case .partialTransfer: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CANCELLATION_REASON_UNSPECIFIED"
      case .serviceTerminated: return "SERVICE_TERMINATED"
      case .relationshipEnded: return "RELATIONSHIP_ENDED"
      case .partialTransfer: return "PARTIAL_TRANSFER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CancellationReason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CANCELLATION_REASON_UNSPECIFIED": self = .unspecified
      case "SERVICE_TERMINATED": self = .serviceTerminated
      case "RELATIONSHIP_ENDED": self = .relationshipEnded
      case "PARTIAL_TRANSFER": self = .partialTransfer
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CancellationReason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .serviceTerminated
      case 2: self = .relationshipEnded
      case 3: self = .partialTransfer
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .serviceTerminated: return try container.encode(1)
      case .relationshipEnded: return try container.encode(2)
      case .partialTransfer: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The Entitlement's activation reason
  public enum ActivationReason: Codable, Equatable, Sendable {
    /// Not used.
    case unspecified
    /// Reseller reactivated a suspended Entitlement.
    case resellerRevokedSuspension
    /// Customer accepted pending terms of service.
    case customerAcceptedPendingTos
    /// Reseller updated the renewal settings on an entitlement that was
    /// suspended due to cancellation, and this update reactivated the
    /// entitlement.
    case renewalSettingsChanged
    /// Other reasons (Activated temporarily for cancellation, added a payment
    /// plan to a trial entitlement, etc.)
    case otherActivationReason
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .resellerRevokedSuspension: return 1
      case .customerAcceptedPendingTos: return 2
      case .renewalSettingsChanged: return 3
      case .otherActivationReason: return 100
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACTIVATION_REASON_UNSPECIFIED"
      case .resellerRevokedSuspension: return "RESELLER_REVOKED_SUSPENSION"
      case .customerAcceptedPendingTos: return "CUSTOMER_ACCEPTED_PENDING_TOS"
      case .renewalSettingsChanged: return "RENEWAL_SETTINGS_CHANGED"
      case .otherActivationReason: return "OTHER_ACTIVATION_REASON"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ActivationReason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACTIVATION_REASON_UNSPECIFIED": self = .unspecified
      case "RESELLER_REVOKED_SUSPENSION": self = .resellerRevokedSuspension
      case "CUSTOMER_ACCEPTED_PENDING_TOS": self = .customerAcceptedPendingTos
      case "RENEWAL_SETTINGS_CHANGED": self = .renewalSettingsChanged
      case "OTHER_ACTIVATION_REASON": self = .otherActivationReason
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ActivationReason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .resellerRevokedSuspension
      case 2: self = .customerAcceptedPendingTos
      case 3: self = .renewalSettingsChanged
      case 100: self = .otherActivationReason
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .resellerRevokedSuspension: return try container.encode(1)
      case .customerAcceptedPendingTos: return try container.encode(2)
      case .renewalSettingsChanged: return try container.encode(3)
      case .otherActivationReason: return try container.encode(100)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The reason the change was made
  public enum OneOf_ChangeReason: Codable, Equatable, Sendable {
    /// Suspension reason for the Entitlement.
    case suspensionReason(Entitlement.SuspensionReason)
    /// Cancellation reason for the Entitlement.
    case cancellationReason(EntitlementChange.CancellationReason)
    /// The Entitlement's activation reason
    case activationReason(EntitlementChange.ActivationReason)
    /// e.g. purchase_number change reason, entered by CRS.
    case otherChangeReason(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.EntitlementChange"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
