// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [CloudChannelReportsService.FetchReportResults][google.cloud.channel.v1.CloudChannelReportsService.FetchReportResults].
///
/// [google.cloud.channel.v1.CloudChannelReportsService.FetchReportResults]: <doc:CloudChannelReportsServiceClient/fetchReportResults(request:)>
@available(*, deprecated)
public struct FetchReportResultsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The report job created by
  /// [CloudChannelReportsService.RunReportJob][google.cloud.channel.v1.CloudChannelReportsService.RunReportJob].
  /// Report_job uses the format:
  /// accounts/{account_id}/reportJobs/{report_job_id}
  ///
  /// [google.cloud.channel.v1.CloudChannelReportsService.RunReportJob]: <doc:CloudChannelReportsServiceClient/runReportJob(request:)>
  public var reportJob: Swift.String = Swift.String()

  /// Optional. Requested page size of the report. The server may return fewer
  /// results than requested. If you don't specify a page size, the server uses a
  /// sensible default (may change over time).
  ///
  /// The maximum value is 30,000; the server will change larger values to
  /// 30,000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token that specifies a page of results beyond the first page.
  /// Obtained through
  /// [FetchReportResultsResponse.next_page_token][google.cloud.channel.v1.FetchReportResultsResponse.next_page_token]
  /// of the previous
  /// [CloudChannelReportsService.FetchReportResults][google.cloud.channel.v1.CloudChannelReportsService.FetchReportResults]
  /// call.
  ///
  /// [google.cloud.channel.v1.CloudChannelReportsService.FetchReportResults]: <doc:CloudChannelReportsServiceClient/fetchReportResults(request:)>
  /// [google.cloud.channel.v1.FetchReportResultsResponse.next_page_token]: <doc:FetchReportResultsResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Optional. List of keys specifying which report partitions to return.
  /// If empty, returns all partitions.
  public var partitionKeys: [Swift.String] = []

  /// Initialize a new instance of `FetchReportResultsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchReportResultsRequest().with { $0.reportJob = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.FetchReportResultsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
