// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [CloudChannelService.ImportCustomer][google.cloud.channel.v1.CloudChannelService.ImportCustomer]
///
/// [google.cloud.channel.v1.CloudChannelService.ImportCustomer]: <doc:CloudChannelServiceClient/importCustomer(request:options:)>
public struct ImportCustomerRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the reseller's account.
  /// Parent takes the format: accounts/{account_id} or
  /// accounts/{account_id}/channelPartnerLinks/{channel_partner_id}
  public var parent: Swift.String = Swift.String()

  /// Optional. The super admin of the resold customer generates this token to
  /// authorize a reseller to access their Cloud Identity and purchase
  /// entitlements on their behalf. You can omit this token after authorization.
  /// See https://support.google.com/a/answer/7643790 for more details.
  public var authToken: Swift.String = Swift.String()

  /// Required. Choose to overwrite an existing customer if found.
  /// This must be set to true if there is an existing customer with a
  /// conflicting region code or domain.
  public var overwriteIfExists: Swift.Bool = Swift.Bool()

  /// Optional. Cloud Identity ID of a channel partner who will be the direct
  /// reseller for the customer's order. This field is required for 2-tier
  /// transfer scenarios and can be provided via the request Parent binding as
  /// well.
  public var channelPartnerId: Swift.String = Swift.String()

  /// Optional. Specifies the customer that will receive imported Cloud Identity
  /// information.
  /// Format: accounts/{account_id}/customers/{customer_id}
  public var customer: Swift.String = Swift.String()

  /// Specifies the identity of the transfer customer.
  /// A customer's cloud_identity_id or domain is required to look up the
  /// customer's Cloud Identity. For Team customers, only the cloud_identity_id
  /// option is valid.
  public var customerIdentity: OneOf_CustomerIdentity? = nil

  /// Initialize a new instance of `ImportCustomerRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportCustomerRequest().with { $0.domain = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case domain = "domain"
    case cloudIdentityId = "cloudIdentityId"
    case primaryAdminEmail = "primaryAdminEmail"
    case parent = "parent"
    case authToken = "authToken"
    case overwriteIfExists = "overwriteIfExists"
    case channelPartnerId = "channelPartnerId"
    case customer = "customer"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.authToken = try container.decode(Swift.String.self, forKey: .authToken)
    self.overwriteIfExists = try container.decode(Swift.Bool.self, forKey: .overwriteIfExists)
    self.channelPartnerId = try container.decode(Swift.String.self, forKey: .channelPartnerId)
    self.customer = try container.decode(Swift.String.self, forKey: .customer)

    var customerIdentity: OneOf_CustomerIdentity? = nil
    let customerIdentityCheckAndSet = {
      if customerIdentity != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'customerIdentity'"))
      }
      customerIdentity = $0
    }
    if let domain = try container.decodeIfPresent(Swift.String.self, forKey: .domain) {
      try customerIdentityCheckAndSet(.domain(domain))
    }
    if let cloudIdentityId = try container.decodeIfPresent(
      Swift.String.self, forKey: .cloudIdentityId)
    {
      try customerIdentityCheckAndSet(.cloudIdentityId(cloudIdentityId))
    }
    if let primaryAdminEmail = try container.decodeIfPresent(
      Swift.String.self, forKey: .primaryAdminEmail)
    {
      try customerIdentityCheckAndSet(.primaryAdminEmail(primaryAdminEmail))
    }
    self.customerIdentity = customerIdentity
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.authToken, forKey: .authToken)
    try container.encode(self.overwriteIfExists, forKey: .overwriteIfExists)
    try container.encode(self.channelPartnerId, forKey: .channelPartnerId)
    try container.encode(self.customer, forKey: .customer)

    if let choice = self.customerIdentity {
      switch choice {
      case .domain(let value):
        try container.encode(value, forKey: .domain)
      case .cloudIdentityId(let value):
        try container.encode(value, forKey: .cloudIdentityId)
      case .primaryAdminEmail(let value):
        try container.encode(value, forKey: .primaryAdminEmail)
      }
    }
  }

  /// Specifies the identity of the transfer customer.
  /// A customer's cloud_identity_id or domain is required to look up the
  /// customer's Cloud Identity. For Team customers, only the cloud_identity_id
  /// option is valid.
  public enum OneOf_CustomerIdentity: Codable, Equatable, Sendable {
    /// Required. Customer domain.
    case domain(Swift.String)
    /// Required. Customer's Cloud Identity ID
    case cloudIdentityId(Swift.String)
    /// Required. Customer's primary admin email.
    case primaryAdminEmail(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ImportCustomerRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
