// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for ListPurchasableOffers.
public struct ListPurchasableOffersRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the customer to list Offers for.
  /// Format: accounts/{account_id}/customers/{customer_id}.
  public var customer: Swift.String = Swift.String()

  /// Optional. Requested page size. Server might return fewer results than
  /// requested. If unspecified, returns at most 100 Offers. The maximum value is
  /// 1000; the server will coerce values above 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token for a page of results other than the first page.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. The BCP-47 language code. For example, "en-US". The
  /// response will localize in the corresponding language code, if specified.
  /// The default value is "en-US".
  public var languageCode: Swift.String = Swift.String()

  /// Defines the intended purchase.
  public var purchaseOption: OneOf_PurchaseOption? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListPurchasableOffersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListPurchasableOffersRequest().with { $0.createEntitlementPurchase = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let createEntitlementPurchase = CodingKeys(stringValue: "createEntitlementPurchase")
    static let changeOfferPurchase = CodingKeys(stringValue: "changeOfferPurchase")
    static let customer = CodingKeys(stringValue: "customer")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let languageCode = CodingKeys(stringValue: "languageCode")

    static let _knownKeys: Set<Swift.String> = [
      "createEntitlementPurchase",
      "changeOfferPurchase",
      "customer",
      "pageSize",
      "pageToken",
      "languageCode",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .customer) {
      self.customer = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageCode) {
      self.languageCode = value
    }

    var purchaseOption: OneOf_PurchaseOption? = nil
    let purchaseOptionCheckAndSet = {
      if purchaseOption != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'purchaseOption'"))
      }
      purchaseOption = $0
    }
    if let createEntitlementPurchase = try container.decodeIfPresent(
      ListPurchasableOffersRequest.CreateEntitlementPurchase?.self,
      forKey: .createEntitlementPurchase)
    {
      try purchaseOptionCheckAndSet(.createEntitlementPurchase(createEntitlementPurchase))
    }
    if let changeOfferPurchase = try container.decodeIfPresent(
      ListPurchasableOffersRequest.ChangeOfferPurchase?.self, forKey: .changeOfferPurchase)
    {
      try purchaseOptionCheckAndSet(.changeOfferPurchase(changeOfferPurchase))
    }
    self.purchaseOption = purchaseOption
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.customer, forKey: .customer)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.languageCode, forKey: .languageCode)

    if let choice = self.purchaseOption {
      switch choice {
      case .createEntitlementPurchase(let value):
        try container.encode(value, forKey: .createEntitlementPurchase)
      case .changeOfferPurchase(let value):
        try container.encode(value, forKey: .changeOfferPurchase)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// List Offers for CreateEntitlement purchase.
  public struct CreateEntitlementPurchase: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. SKU that the result should be restricted to.
    /// Format: products/{product_id}/skus/{sku_id}.
    public var sku: Swift.String = Swift.String()

    /// Optional. Billing account that the result should be restricted to.
    /// Format: accounts/{account_id}/billingAccounts/{billing_account_id}.
    public var billingAccount: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `CreateEntitlementPurchase`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CreateEntitlementPurchase().with { $0.sku = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sku = CodingKeys(stringValue: "sku")
      static let billingAccount = CodingKeys(stringValue: "billingAccount")

      static let _knownKeys: Set<Swift.String> = [
        "sku",
        "billingAccount",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sku) {
        self.sku = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .billingAccount) {
        self.billingAccount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sku, forKey: .sku)
      try container.encode(self.billingAccount, forKey: .billingAccount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.channel.v1.ListPurchasableOffersRequest.CreateEntitlementPurchase"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// List Offers for ChangeOffer purchase.
  public struct ChangeOfferPurchase: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Resource name of the entitlement.
    /// Format:
    /// accounts/{account_id}/customers/{customer_id}/entitlements/{entitlement_id}
    public var entitlement: Swift.String = Swift.String()

    /// Optional. Resource name of the new target SKU. Provide this SKU when
    /// upgrading or downgrading an entitlement. Format:
    /// products/{product_id}/skus/{sku_id}
    public var newSku: Swift.String = Swift.String()

    /// Optional. Resource name of the new target Billing Account. Provide this
    /// Billing Account when setting up billing for a trial subscription. Format:
    /// accounts/{account_id}/billingAccounts/{billing_account_id}.
    ///
    /// This field is only relevant for multi-currency accounts. It should be
    /// left empty for single currency accounts.
    public var billingAccount: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `ChangeOfferPurchase`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ChangeOfferPurchase().with { $0.entitlement = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let entitlement = CodingKeys(stringValue: "entitlement")
      static let newSku = CodingKeys(stringValue: "newSku")
      static let billingAccount = CodingKeys(stringValue: "billingAccount")

      static let _knownKeys: Set<Swift.String> = [
        "entitlement",
        "newSku",
        "billingAccount",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entitlement) {
        self.entitlement = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .newSku) {
        self.newSku = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .billingAccount) {
        self.billingAccount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.entitlement, forKey: .entitlement)
      try container.encode(self.newSku, forKey: .newSku)
      try container.encode(self.billingAccount, forKey: .billingAccount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.channel.v1.ListPurchasableOffersRequest.ChangeOfferPurchase"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines the intended purchase.
  public enum OneOf_PurchaseOption: Codable, Equatable, Sendable {
    /// List Offers for CreateEntitlement purchase.
    indirect case createEntitlementPurchase(ListPurchasableOffersRequest.CreateEntitlementPurchase?)
    /// List Offers for ChangeOffer purchase.
    indirect case changeOfferPurchase(ListPurchasableOffersRequest.ChangeOfferPurchase?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ListPurchasableOffersRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
