// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [CloudChannelService.ListTransferableSkus][google.cloud.channel.v1.CloudChannelService.ListTransferableSkus]
///
/// [google.cloud.channel.v1.CloudChannelService.ListTransferableSkus]: <doc:CloudChannelServiceClient/listTransferableSkus(request:options:)>
public struct ListTransferableSkusRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The reseller account's resource name.
  /// Parent uses the format: accounts/{account_id}
  public var parent: Swift.String = Swift.String()

  /// The requested page size. Server might return fewer results than requested.
  /// If unspecified, returns at most 100 SKUs.
  /// The maximum value is 1000; the server will coerce values above 1000.
  /// Optional.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A token for a page of results other than the first page.
  /// Obtained using
  /// [ListTransferableSkusResponse.next_page_token][google.cloud.channel.v1.ListTransferableSkusResponse.next_page_token]
  /// of the previous
  /// [CloudChannelService.ListTransferableSkus][google.cloud.channel.v1.CloudChannelService.ListTransferableSkus]
  /// call. Optional.
  ///
  /// [google.cloud.channel.v1.CloudChannelService.ListTransferableSkus]: <doc:CloudChannelServiceClient/listTransferableSkus(request:options:)>
  /// [google.cloud.channel.v1.ListTransferableSkusResponse.next_page_token]: <doc:ListTransferableSkusResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Optional. The super admin of the resold customer generates this token to
  /// authorize a reseller to access their Cloud Identity and purchase
  /// entitlements on their behalf. You can omit this token after authorization.
  /// See https://support.google.com/a/answer/7643790 for more details.
  public var authToken: Swift.String = Swift.String()

  /// The BCP-47 language code. For example, "en-US". The
  /// response will localize in the corresponding language code, if specified.
  /// The default value is "en-US".
  /// Optional.
  public var languageCode: Swift.String = Swift.String()

  /// Specifies the identity of transferred customer.
  /// Either a cloud_identity_id of the customer or the customer name is
  /// required to look up transferable SKUs.
  public var transferredCustomerIdentity: OneOf_TransferredCustomerIdentity? = nil

  /// Initialize a new instance of `ListTransferableSkusRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListTransferableSkusRequest().with { $0.cloudIdentityId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case cloudIdentityId = "cloudIdentityId"
    case customerName = "customerName"
    case parent = "parent"
    case pageSize = "pageSize"
    case pageToken = "pageToken"
    case authToken = "authToken"
    case languageCode = "languageCode"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.pageSize = try container.decode(Swift.Int32.self, forKey: .pageSize)
    self.pageToken = try container.decode(Swift.String.self, forKey: .pageToken)
    self.authToken = try container.decode(Swift.String.self, forKey: .authToken)
    self.languageCode = try container.decode(Swift.String.self, forKey: .languageCode)

    var transferredCustomerIdentity: OneOf_TransferredCustomerIdentity? = nil
    let transferredCustomerIdentityCheckAndSet = {
      if transferredCustomerIdentity != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'transferredCustomerIdentity'"))
      }
      transferredCustomerIdentity = $0
    }
    if let cloudIdentityId = try container.decodeIfPresent(
      Swift.String.self, forKey: .cloudIdentityId)
    {
      try transferredCustomerIdentityCheckAndSet(.cloudIdentityId(cloudIdentityId))
    }
    if let customerName = try container.decodeIfPresent(Swift.String.self, forKey: .customerName) {
      try transferredCustomerIdentityCheckAndSet(.customerName(customerName))
    }
    self.transferredCustomerIdentity = transferredCustomerIdentity
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.authToken, forKey: .authToken)
    try container.encode(self.languageCode, forKey: .languageCode)

    if let choice = self.transferredCustomerIdentity {
      switch choice {
      case .cloudIdentityId(let value):
        try container.encode(value, forKey: .cloudIdentityId)
      case .customerName(let value):
        try container.encode(value, forKey: .customerName)
      }
    }
  }

  /// Specifies the identity of transferred customer.
  /// Either a cloud_identity_id of the customer or the customer name is
  /// required to look up transferable SKUs.
  public enum OneOf_TransferredCustomerIdentity: Codable, Equatable, Sendable {
    /// Customer's Cloud Identity ID
    case cloudIdentityId(Swift.String)
    /// A reseller is required to create a customer and use the resource name of
    /// the created customer here.
    /// Customer_name uses the format:
    /// accounts/{account_id}/customers/{customer_id}
    case customerName(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ListTransferableSkusRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
