// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for ListPurchasableSkus.
public struct ListPurchasableSkusRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the customer to list SKUs for.
  /// Format: accounts/{account_id}/customers/{customer_id}.
  public var customer: Swift.String = Swift.String()

  /// Optional. Requested page size. Server might return fewer results than
  /// requested. If unspecified, returns at most 100 SKUs. The maximum value is
  /// 1000; the server will coerce values above 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token for a page of results other than the first page.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. The BCP-47 language code. For example, "en-US". The
  /// response will localize in the corresponding language code, if specified.
  /// The default value is "en-US".
  public var languageCode: Swift.String = Swift.String()

  /// Defines the intended purchase.
  public var purchaseOption: OneOf_PurchaseOption? = nil

  /// Initialize a new instance of `ListPurchasableSkusRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListPurchasableSkusRequest().with { $0.createEntitlementPurchase = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case createEntitlementPurchase = "createEntitlementPurchase"
    case changeOfferPurchase = "changeOfferPurchase"
    case customer = "customer"
    case pageSize = "pageSize"
    case pageToken = "pageToken"
    case languageCode = "languageCode"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.customer = try container.decode(Swift.String.self, forKey: .customer)
    self.pageSize = try container.decode(Swift.Int32.self, forKey: .pageSize)
    self.pageToken = try container.decode(Swift.String.self, forKey: .pageToken)
    self.languageCode = try container.decode(Swift.String.self, forKey: .languageCode)

    var purchaseOption: OneOf_PurchaseOption? = nil
    let purchaseOptionCheckAndSet = {
      if purchaseOption != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'purchaseOption'"))
      }
      purchaseOption = $0
    }
    if let createEntitlementPurchase = try container.decodeIfPresent(
      ListPurchasableSkusRequest.CreateEntitlementPurchase?.self, forKey: .createEntitlementPurchase
    ) {
      try purchaseOptionCheckAndSet(.createEntitlementPurchase(createEntitlementPurchase))
    }
    if let changeOfferPurchase = try container.decodeIfPresent(
      ListPurchasableSkusRequest.ChangeOfferPurchase?.self, forKey: .changeOfferPurchase)
    {
      try purchaseOptionCheckAndSet(.changeOfferPurchase(changeOfferPurchase))
    }
    self.purchaseOption = purchaseOption
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.customer, forKey: .customer)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.languageCode, forKey: .languageCode)

    if let choice = self.purchaseOption {
      switch choice {
      case .createEntitlementPurchase(let value):
        try container.encode(value, forKey: .createEntitlementPurchase)
      case .changeOfferPurchase(let value):
        try container.encode(value, forKey: .changeOfferPurchase)
      }
    }
  }

  /// List SKUs for a new entitlement. Make the purchase using
  /// [CloudChannelService.CreateEntitlement][google.cloud.channel.v1.CloudChannelService.CreateEntitlement].
  ///
  /// [google.cloud.channel.v1.CloudChannelService.CreateEntitlement]: <doc:CloudChannelServiceClient/createEntitlement(request:options:)>
  public struct CreateEntitlementPurchase: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. List SKUs belonging to this Product.
    /// Format: products/{product_id}.
    /// Supports products/- to retrieve SKUs for all products.
    public var product: Swift.String = Swift.String()

    /// Initialize a new instance of `CreateEntitlementPurchase`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CreateEntitlementPurchase().with { $0.product = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.channel.v1.ListPurchasableSkusRequest.CreateEntitlementPurchase"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// List SKUs for upgrading or downgrading an entitlement. Make the purchase
  /// using
  /// [CloudChannelService.ChangeOffer][google.cloud.channel.v1.CloudChannelService.ChangeOffer].
  ///
  /// [google.cloud.channel.v1.CloudChannelService.ChangeOffer]: <doc:CloudChannelServiceClient/changeOffer(request:options:)>
  public struct ChangeOfferPurchase: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Resource name of the entitlement.
    /// Format:
    /// accounts/{account_id}/customers/{customer_id}/entitlements/{entitlement_id}
    public var entitlement: Swift.String = Swift.String()

    /// Required. Change Type for the entitlement.
    public var changeType: ListPurchasableSkusRequest.ChangeOfferPurchase.ChangeType =
      ListPurchasableSkusRequest.ChangeOfferPurchase.ChangeType()

    /// Initialize a new instance of `ChangeOfferPurchase`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ChangeOfferPurchase().with { $0.entitlement = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Change Type enum.
    public enum ChangeType: Codable, Equatable, Sendable {
      /// Not used.
      case unspecified
      /// SKU is an upgrade on the current entitlement.
      case upgrade
      /// SKU is a downgrade on the current entitlement.
      case downgrade
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .upgrade: return 1
        case .downgrade: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CHANGE_TYPE_UNSPECIFIED"
        case .upgrade: return "UPGRADE"
        case .downgrade: return "DOWNGRADE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ChangeType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CHANGE_TYPE_UNSPECIFIED": self = .unspecified
        case "UPGRADE": self = .upgrade
        case "DOWNGRADE": self = .downgrade
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ChangeType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .upgrade
        case 2: self = .downgrade
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .upgrade: return try container.encode(1)
        case .downgrade: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.channel.v1.ListPurchasableSkusRequest.ChangeOfferPurchase"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines the intended purchase.
  public enum OneOf_PurchaseOption: Codable, Equatable, Sendable {
    /// List SKUs for CreateEntitlement purchase.
    indirect case createEntitlementPurchase(ListPurchasableSkusRequest.CreateEntitlementPurchase?)
    /// List SKUs for ChangeOffer purchase with a new SKU.
    indirect case changeOfferPurchase(ListPurchasableSkusRequest.ChangeOfferPurchase?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ListPurchasableSkusRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
