// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [CloudChannelReportsService.ListReports][google.cloud.channel.v1.CloudChannelReportsService.ListReports].
///
/// [google.cloud.channel.v1.CloudChannelReportsService.ListReports]: <doc:CloudChannelReportsServiceClient/listReports(request:)>
@available(*, deprecated)
public struct ListReportsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the partner account to list available
  /// reports for. Parent uses the format: accounts/{account_id}
  public var parent: Swift.String = Swift.String()

  /// Optional. Requested page size of the report. The server might return fewer
  /// results than requested. If unspecified, returns 20 reports. The maximum
  /// value is 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token that specifies a page of results beyond the first page.
  /// Obtained through
  /// [ListReportsResponse.next_page_token][google.cloud.channel.v1.ListReportsResponse.next_page_token]
  /// of the previous
  /// [CloudChannelReportsService.ListReports][google.cloud.channel.v1.CloudChannelReportsService.ListReports]
  /// call.
  ///
  /// [google.cloud.channel.v1.CloudChannelReportsService.ListReports]: <doc:CloudChannelReportsServiceClient/listReports(request:)>
  /// [google.cloud.channel.v1.ListReportsResponse.next_page_token]: <doc:ListReportsResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Optional. The BCP-47 language code, such as "en-US".  If specified, the
  /// response is localized to the corresponding language code if the
  /// original data sources support it.
  /// Default is "en-US".
  public var languageCode: Swift.String = Swift.String()

  /// Initialize a new instance of `ListReportsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListReportsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ListReportsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
