// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [CloudChannelService.ListEntitlements][google.cloud.channel.v1.CloudChannelService.ListEntitlements]
///
/// [google.cloud.channel.v1.CloudChannelService.ListEntitlements]: <doc:CloudChannelServiceClient/listEntitlements(request:)>
public struct ListEntitlementsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the reseller's customer account to list
  /// entitlements for.
  /// Parent uses the format: accounts/{account_id}/customers/{customer_id}
  public var parent: Swift.String = Swift.String()

  /// Optional. Requested page size. Server might return fewer results than
  /// requested. If unspecified, return at most 50 entitlements. The maximum
  /// value is 100; the server will coerce values above 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token for a page of results other than the first page.
  /// Obtained using
  /// [ListEntitlementsResponse.next_page_token][google.cloud.channel.v1.ListEntitlementsResponse.next_page_token]
  /// of the previous
  /// [CloudChannelService.ListEntitlements][google.cloud.channel.v1.CloudChannelService.ListEntitlements]
  /// call.
  ///
  /// [google.cloud.channel.v1.CloudChannelService.ListEntitlements]: <doc:CloudChannelServiceClient/listEntitlements(request:)>
  /// [google.cloud.channel.v1.ListEntitlementsResponse.next_page_token]: <doc:ListEntitlementsResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListEntitlementsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListEntitlementsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ListEntitlementsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
