// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [CloudChannelService.ListEntitlementChanges][google.cloud.channel.v1.CloudChannelService.ListEntitlementChanges]
///
/// [google.cloud.channel.v1.CloudChannelService.ListEntitlementChanges]: <doc:CloudChannelServiceClient/listEntitlementChanges(request:options:)>
public struct ListEntitlementChangesRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the entitlement for which to list
  /// entitlement changes. The `-` wildcard may be used to match entitlements
  /// across a customer. Formats:
  ///
  ///   * accounts/{account_id}/customers/{customer_id}/entitlements/{entitlement_id}
  ///   * accounts/{account_id}/customers/{customer_id}/entitlements/-
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of entitlement changes to return. The service
  /// may return fewer than this value. If unspecified, returns at most 10
  /// entitlement changes. The maximum value is 50; the server will coerce values
  /// above 50.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous
  /// [CloudChannelService.ListEntitlementChanges][google.cloud.channel.v1.CloudChannelService.ListEntitlementChanges]
  /// call. Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// [CloudChannelService.ListEntitlementChanges][google.cloud.channel.v1.CloudChannelService.ListEntitlementChanges]
  /// must match the call that provided the page token.
  ///
  /// [google.cloud.channel.v1.CloudChannelService.ListEntitlementChanges]: <doc:CloudChannelServiceClient/listEntitlementChanges(request:options:)>
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Filters applied to the list results.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListEntitlementChangesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListEntitlementChangesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ListEntitlementChangesRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
