// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for ListPurchasableOffers.
public struct ListPurchasableOffersRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the customer to list Offers for.
  /// Format: accounts/{account_id}/customers/{customer_id}.
  public var customer: Swift.String = Swift.String()

  /// Optional. Requested page size. Server might return fewer results than
  /// requested. If unspecified, returns at most 100 Offers. The maximum value is
  /// 1000; the server will coerce values above 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token for a page of results other than the first page.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. The BCP-47 language code. For example, "en-US". The
  /// response will localize in the corresponding language code, if specified.
  /// The default value is "en-US".
  public var languageCode: Swift.String = Swift.String()

  /// Defines the intended purchase.
  public var purchaseOption: OneOf_PurchaseOption? = nil

  /// Initialize a new instance of `ListPurchasableOffersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListPurchasableOffersRequest().with { $0.createEntitlementPurchase = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case createEntitlementPurchase = "createEntitlementPurchase"
    case changeOfferPurchase = "changeOfferPurchase"
    case customer = "customer"
    case pageSize = "pageSize"
    case pageToken = "pageToken"
    case languageCode = "languageCode"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.customer = try container.decode(Swift.String.self, forKey: .customer)
    self.pageSize = try container.decode(Swift.Int32.self, forKey: .pageSize)
    self.pageToken = try container.decode(Swift.String.self, forKey: .pageToken)
    self.languageCode = try container.decode(Swift.String.self, forKey: .languageCode)

    var purchaseOption: OneOf_PurchaseOption? = nil
    let purchaseOptionCheckAndSet = {
      if purchaseOption != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'purchaseOption'"))
      }
      purchaseOption = $0
    }
    if let createEntitlementPurchase = try container.decodeIfPresent(
      ListPurchasableOffersRequest.CreateEntitlementPurchase?.self,
      forKey: .createEntitlementPurchase)
    {
      try purchaseOptionCheckAndSet(.createEntitlementPurchase(createEntitlementPurchase))
    }
    if let changeOfferPurchase = try container.decodeIfPresent(
      ListPurchasableOffersRequest.ChangeOfferPurchase?.self, forKey: .changeOfferPurchase)
    {
      try purchaseOptionCheckAndSet(.changeOfferPurchase(changeOfferPurchase))
    }
    self.purchaseOption = purchaseOption
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.customer, forKey: .customer)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.languageCode, forKey: .languageCode)

    if let choice = self.purchaseOption {
      switch choice {
      case .createEntitlementPurchase(let value):
        try container.encode(value, forKey: .createEntitlementPurchase)
      case .changeOfferPurchase(let value):
        try container.encode(value, forKey: .changeOfferPurchase)
      }
    }
  }

  /// List Offers for CreateEntitlement purchase.
  public struct CreateEntitlementPurchase: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. SKU that the result should be restricted to.
    /// Format: products/{product_id}/skus/{sku_id}.
    public var sku: Swift.String = Swift.String()

    /// Optional. Billing account that the result should be restricted to.
    /// Format: accounts/{account_id}/billingAccounts/{billing_account_id}.
    public var billingAccount: Swift.String = Swift.String()

    /// Initialize a new instance of `CreateEntitlementPurchase`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CreateEntitlementPurchase().with { $0.sku = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.channel.v1.ListPurchasableOffersRequest.CreateEntitlementPurchase"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// List Offers for ChangeOffer purchase.
  public struct ChangeOfferPurchase: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Resource name of the entitlement.
    /// Format:
    /// accounts/{account_id}/customers/{customer_id}/entitlements/{entitlement_id}
    public var entitlement: Swift.String = Swift.String()

    /// Optional. Resource name of the new target SKU. Provide this SKU when
    /// upgrading or downgrading an entitlement. Format:
    /// products/{product_id}/skus/{sku_id}
    public var newSku: Swift.String = Swift.String()

    /// Optional. Resource name of the new target Billing Account. Provide this
    /// Billing Account when setting up billing for a trial subscription. Format:
    /// accounts/{account_id}/billingAccounts/{billing_account_id}.
    ///
    /// This field is only relevant for multi-currency accounts. It should be
    /// left empty for single currency accounts.
    public var billingAccount: Swift.String = Swift.String()

    /// Initialize a new instance of `ChangeOfferPurchase`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ChangeOfferPurchase().with { $0.entitlement = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.channel.v1.ListPurchasableOffersRequest.ChangeOfferPurchase"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines the intended purchase.
  public enum OneOf_PurchaseOption: Codable, Equatable, Sendable {
    /// List Offers for CreateEntitlement purchase.
    indirect case createEntitlementPurchase(ListPurchasableOffersRequest.CreateEntitlementPurchase?)
    /// List Offers for ChangeOffer purchase.
    indirect case changeOfferPurchase(ListPurchasableOffersRequest.ChangeOfferPurchase?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ListPurchasableOffersRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
