// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for
/// [CloudChannelService.ListChannelPartnerLinks][google.cloud.channel.v1.CloudChannelService.ListChannelPartnerLinks].
///
/// [google.cloud.channel.v1.CloudChannelService.ListChannelPartnerLinks]: <doc:CloudChannelServiceClient/listChannelPartnerLinks(request:options:)>
public struct ListChannelPartnerLinksResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The Channel partner links for a reseller.
  public var channelPartnerLinks: [ChannelPartnerLink] = []

  /// A token to retrieve the next page of results.
  /// Pass to
  /// [ListChannelPartnerLinksRequest.page_token][google.cloud.channel.v1.ListChannelPartnerLinksRequest.page_token]
  /// to obtain that page.
  ///
  /// [google.cloud.channel.v1.ListChannelPartnerLinksRequest.page_token]: <doc:ListChannelPartnerLinksRequest/pageToken>
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListChannelPartnerLinksResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListChannelPartnerLinksResponse().with { $0.channelPartnerLinks = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ListChannelPartnerLinksResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [ChannelPartnerLink] {
    return self.channelPartnerLinks
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
