// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// Response message for
/// [CloudChannelService.ListCustomers][google.cloud.channel.v1.CloudChannelService.ListCustomers].
///
/// [google.cloud.channel.v1.CloudChannelService.ListCustomers]: <doc:CloudChannelServiceClient/listCustomers(request:)>
public struct ListCustomersResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The customers belonging to a reseller or distributor.
  public var customers: [Customer] = []

  /// A token to retrieve the next page of results.
  /// Pass to
  /// [ListCustomersRequest.page_token][google.cloud.channel.v1.ListCustomersRequest.page_token]
  /// to obtain that page.
  ///
  /// [google.cloud.channel.v1.ListCustomersRequest.page_token]: <doc:ListCustomersRequest/pageToken>
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListCustomersResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCustomersResponse().with { $0.customers = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ListCustomersResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [Customer] {
    return self.customers
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
