// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents an offer made to resellers for purchase.
/// An offer is associated with a [Sku][google.cloud.channel.v1.Sku], has a plan
/// for payment, a price, and defines the constraints for buying.
///
/// [google.cloud.channel.v1.Sku]: <doc:Sku>
public struct Offer: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Resource Name of the Offer.
  /// Format: accounts/{account_id}/offers/{offer_id}
  public var name: Swift.String = Swift.String()

  /// Marketing information for the Offer.
  public var marketingInfo: MarketingInfo? = nil

  /// SKU the offer is associated with.
  public var sku: Sku? = nil

  /// Describes the payment plan for the Offer.
  public var plan: Plan? = nil

  /// Constraints on transacting the Offer.
  public var constraints: Constraints? = nil

  /// Price for each monetizable resource type.
  public var priceByResources: [PriceByResource] = []

  /// Start of the Offer validity time.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. End of the Offer validity time.
  public var endTime: GoogleCloudWKT.Timestamp? = nil

  /// Parameters required to use current Offer to purchase.
  public var parameterDefinitions: [ParameterDefinition] = []

  /// The deal code of the offer to get a special promotion or discount.
  public var dealCode: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Offer`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Offer().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let marketingInfo = CodingKeys(stringValue: "marketingInfo")
    static let sku = CodingKeys(stringValue: "sku")
    static let plan = CodingKeys(stringValue: "plan")
    static let constraints = CodingKeys(stringValue: "constraints")
    static let priceByResources = CodingKeys(stringValue: "priceByResources")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let parameterDefinitions = CodingKeys(stringValue: "parameterDefinitions")
    static let dealCode = CodingKeys(stringValue: "dealCode")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "marketingInfo",
      "sku",
      "plan",
      "constraints",
      "priceByResources",
      "startTime",
      "endTime",
      "parameterDefinitions",
      "dealCode",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.marketingInfo = try container.decodeIfPresent(MarketingInfo.self, forKey: .marketingInfo)
    self.sku = try container.decodeIfPresent(Sku.self, forKey: .sku)
    self.plan = try container.decodeIfPresent(Plan.self, forKey: .plan)
    self.constraints = try container.decodeIfPresent(Constraints.self, forKey: .constraints)
    if let value = try container.decodeIfPresent([PriceByResource].self, forKey: .priceByResources)
    {
      self.priceByResources = value
    }
    self.startTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleCloudWKT.Timestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(
      [ParameterDefinition].self, forKey: .parameterDefinitions)
    {
      self.parameterDefinitions = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dealCode) {
      self.dealCode = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.marketingInfo, forKey: .marketingInfo)
    try container.encodeIfPresent(self.sku, forKey: .sku)
    try container.encodeIfPresent(self.plan, forKey: .plan)
    try container.encodeIfPresent(self.constraints, forKey: .constraints)
    try container.encode(self.priceByResources, forKey: .priceByResources)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.parameterDefinitions, forKey: .parameterDefinitions)
    try container.encode(self.dealCode, forKey: .dealCode)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.Offer"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
