// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Parameter's definition. Specifies what parameter is required to use the
/// current Offer to purchase.
public struct ParameterDefinition: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of the parameter.
  public var name: Swift.String = Swift.String()

  /// Data type of the parameter. Minimal value, Maximum value and allowed values
  /// will use specified data type here.
  public var parameterType: ParameterDefinition.ParameterType = ParameterDefinition.ParameterType()

  /// Minimal value of the parameter, if applicable. Inclusive. For example,
  /// minimal commitment when purchasing Anthos is 0.01.
  /// Applicable to INT64 and DOUBLE parameter types.
  public var minValue: Value? = nil

  /// Maximum value of the parameter, if applicable. Inclusive. For example,
  /// maximum seats when purchasing Google Workspace Business Standard.
  /// Applicable to INT64 and DOUBLE parameter types.
  public var maxValue: Value? = nil

  /// If not empty, parameter values must be drawn from this list.
  /// For example, [us-west1, us-west2, ...]
  /// Applicable to STRING parameter type.
  public var allowedValues: [Value] = []

  /// If set to true, parameter is optional to purchase this Offer.
  public var `optional`: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ParameterDefinition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ParameterDefinition().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let parameterType = CodingKeys(stringValue: "parameterType")
    static let minValue = CodingKeys(stringValue: "minValue")
    static let maxValue = CodingKeys(stringValue: "maxValue")
    static let allowedValues = CodingKeys(stringValue: "allowedValues")
    static let `optional` = CodingKeys(stringValue: "optional")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "parameterType",
      "minValue",
      "maxValue",
      "allowedValues",
      "optional",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(
      ParameterDefinition.ParameterType.self, forKey: .parameterType)
    {
      self.parameterType = value
    }
    self.minValue = try container.decodeIfPresent(Value.self, forKey: .minValue)
    self.maxValue = try container.decodeIfPresent(Value.self, forKey: .maxValue)
    if let value = try container.decodeIfPresent([Value].self, forKey: .allowedValues) {
      self.allowedValues = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .`optional`) {
      self.`optional` = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.parameterType, forKey: .parameterType)
    try container.encodeIfPresent(self.minValue, forKey: .minValue)
    try container.encodeIfPresent(self.maxValue, forKey: .maxValue)
    try container.encode(self.allowedValues, forKey: .allowedValues)
    try container.encode(self.`optional`, forKey: .`optional`)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Data type of the parameter.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ParameterType: Codable, Equatable, Sendable {
    /// Not used.
    case unspecified
    /// Int64 type.
    case int64
    /// String type.
    case string
    /// Double type.
    case double
    /// Boolean type.
    case boolean
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .int64: return 1
      case .string: return 2
      case .double: return 3
      case .boolean: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PARAMETER_TYPE_UNSPECIFIED"
      case .int64: return "INT64"
      case .string: return "STRING"
      case .double: return "DOUBLE"
      case .boolean: return "BOOLEAN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ParameterType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PARAMETER_TYPE_UNSPECIFIED": self = .unspecified
      case "INT64": self = .int64
      case "STRING": self = .string
      case "DOUBLE": self = .double
      case "BOOLEAN": self = .boolean
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ParameterType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .int64
      case 2: self = .string
      case 3: self = .double
      case 4: self = .boolean
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PARAMETER_TYPE_UNSPECIFIED")
      case .int64: return try container.encode("INT64")
      case .string: return try container.encode("STRING")
      case .double: return try container.encode("DOUBLE")
      case .boolean: return try container.encode("BOOLEAN")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ParameterDefinition"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
