// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Describes how the reseller will be billed.
public enum PaymentPlan: Codable, Equatable, Sendable {
  /// Not used.
  case unspecified
  /// Commitment.
  case commitment
  /// No commitment.
  case flexible
  /// Free.
  case free
  /// Trial.
  case trial
  /// Price and ordering not available through API.
  case offline
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .commitment: return 1
    case .flexible: return 2
    case .free: return 3
    case .trial: return 4
    case .offline: return 5
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "PAYMENT_PLAN_UNSPECIFIED"
    case .commitment: return "COMMITMENT"
    case .flexible: return "FLEXIBLE"
    case .free: return "FREE"
    case .trial: return "TRIAL"
    case .offline: return "OFFLINE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PaymentPlan/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "PAYMENT_PLAN_UNSPECIFIED": self = .unspecified
    case "COMMITMENT": self = .commitment
    case "FLEXIBLE": self = .flexible
    case "FREE": self = .free
    case "TRIAL": self = .trial
    case "OFFLINE": self = .offline
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PaymentPlan/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .commitment
    case 2: self = .flexible
    case 3: self = .free
    case 4: self = .trial
    case 5: self = .offline
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .commitment: return try container.encode(1)
    case .flexible: return try container.encode(2)
    case .free: return try container.encode(3)
    case .trial: return try container.encode(4)
    case .offline: return try container.encode(5)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
