// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents the price of the Offer.
public struct Price: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Base price.
  public var basePrice: GoogleType.Money? = nil

  /// Discount percentage, represented as decimal.
  /// For example, a 20% discount will be represent as 0.2.
  public var discount: Swift.Double = Swift.Double()

  /// Effective Price after applying the discounts.
  public var effectivePrice: GoogleType.Money? = nil

  /// The time period with respect to which base and effective prices are
  /// defined.
  /// Example: 1 month, 6 months, 1 year, etc.
  public var pricePeriod: Period? = nil

  /// Link to external price list, such as link to Google Voice rate card.
  public var externalPriceUri: Swift.String = Swift.String()

  /// Breakdown of the discount into its components.
  /// This will be empty if there is no discount present.
  public var discountComponents: [DiscountComponent] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Price`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Price().with { $0.basePrice = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let basePrice = CodingKeys(stringValue: "basePrice")
    static let discount = CodingKeys(stringValue: "discount")
    static let effectivePrice = CodingKeys(stringValue: "effectivePrice")
    static let pricePeriod = CodingKeys(stringValue: "pricePeriod")
    static let externalPriceUri = CodingKeys(stringValue: "externalPriceUri")
    static let discountComponents = CodingKeys(stringValue: "discountComponents")

    static let _knownKeys: Set<Swift.String> = [
      "basePrice",
      "discount",
      "effectivePrice",
      "pricePeriod",
      "externalPriceUri",
      "discountComponents",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.basePrice = try container.decodeIfPresent(GoogleType.Money.self, forKey: .basePrice)
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .discount) {
      self.discount = value
    }
    self.effectivePrice = try container.decodeIfPresent(
      GoogleType.Money.self, forKey: .effectivePrice)
    self.pricePeriod = try container.decodeIfPresent(Period.self, forKey: .pricePeriod)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .externalPriceUri) {
      self.externalPriceUri = value
    }
    if let value = try container.decodeIfPresent(
      [DiscountComponent].self, forKey: .discountComponents)
    {
      self.discountComponents = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.basePrice, forKey: .basePrice)
    try container.encode(self.discount, forKey: .discount)
    try container.encodeIfPresent(self.effectivePrice, forKey: .effectivePrice)
    try container.encodeIfPresent(self.pricePeriod, forKey: .pricePeriod)
    try container.encode(self.externalPriceUri, forKey: .externalPriceUri)
    try container.encode(self.discountComponents, forKey: .discountComponents)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.Price"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
