// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Service provisioned for an entitlement.
public struct ProvisionedService: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Provisioning ID of the entitlement. For Google Workspace, this
  /// is the underlying Subscription ID. For Google Cloud, this is the Billing
  /// Account ID of the billing subaccount.
  public var provisioningId: Swift.String = Swift.String()

  /// Output only. The product pertaining to the provisioning resource as
  /// specified in the Offer.
  public var productId: Swift.String = Swift.String()

  /// Output only. The SKU pertaining to the provisioning resource as specified
  /// in the Offer.
  public var skuId: Swift.String = Swift.String()

  /// Initialize a new instance of `ProvisionedService`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProvisionedService().with { $0.provisioningId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.ProvisionedService"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
