// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Renewal settings for renewable Offers.
public struct RenewalSettings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// If false, the plan will be completed at the end date.
  public var enableRenewal: Swift.Bool = Swift.Bool()

  /// If true and enable_renewal = true, the unit (for example seats or licenses)
  /// will be set to the number of active units at renewal time.
  public var resizeUnitCount: Swift.Bool = Swift.Bool()

  /// Describes how a reseller will be billed.
  public var paymentPlan: PaymentPlan = PaymentPlan()

  /// Describes how frequently the reseller will be billed, such as
  /// once per month.
  public var paymentCycle: Period? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `RenewalSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RenewalSettings().with { $0.enableRenewal = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enableRenewal = CodingKeys(stringValue: "enableRenewal")
    static let resizeUnitCount = CodingKeys(stringValue: "resizeUnitCount")
    static let paymentPlan = CodingKeys(stringValue: "paymentPlan")
    static let paymentCycle = CodingKeys(stringValue: "paymentCycle")

    static let _knownKeys: Set<Swift.String> = [
      "enableRenewal",
      "resizeUnitCount",
      "paymentPlan",
      "paymentCycle",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableRenewal) {
      self.enableRenewal = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .resizeUnitCount) {
      self.resizeUnitCount = value
    }
    if let value = try container.decodeIfPresent(PaymentPlan.self, forKey: .paymentPlan) {
      self.paymentPlan = value
    }
    self.paymentCycle = try container.decodeIfPresent(Period.self, forKey: .paymentCycle)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.enableRenewal, forKey: .enableRenewal)
    try container.encode(self.resizeUnitCount, forKey: .resizeUnitCount)
    try container.encode(self.paymentPlan, forKey: .paymentPlan)
    try container.encodeIfPresent(self.paymentCycle, forKey: .paymentCycle)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.RenewalSettings"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
