// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Renewal settings for renewable Offers.
public struct RenewalSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// If false, the plan will be completed at the end date.
  public var enableRenewal: Swift.Bool = Swift.Bool()

  /// If true and enable_renewal = true, the unit (for example seats or licenses)
  /// will be set to the number of active units at renewal time.
  public var resizeUnitCount: Swift.Bool = Swift.Bool()

  /// Describes how a reseller will be billed.
  public var paymentPlan: PaymentPlan = PaymentPlan()

  /// Describes how frequently the reseller will be billed, such as
  /// once per month.
  public var paymentCycle: Period? = nil

  /// Initialize a new instance of `RenewalSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RenewalSettings().with { $0.enableRenewal = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.RenewalSettings"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
