// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A type that represents the various adjustments you can apply to a bill.
public struct RepricingAdjustment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A oneof that represents the different types for this adjustment.
  public var adjustment: OneOf_Adjustment? = nil

  /// Initialize a new instance of `RepricingAdjustment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RepricingAdjustment().with { $0.percentageAdjustment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case percentageAdjustment = "percentageAdjustment"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var adjustment: OneOf_Adjustment? = nil
    let adjustmentCheckAndSet = {
      if adjustment != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'adjustment'"))
      }
      adjustment = $0
    }
    if let percentageAdjustment = try container.decodeIfPresent(
      PercentageAdjustment?.self, forKey: .percentageAdjustment)
    {
      try adjustmentCheckAndSet(.percentageAdjustment(percentageAdjustment))
    }
    self.adjustment = adjustment
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.adjustment {
      switch choice {
      case .percentageAdjustment(let value):
        try container.encode(value, forKey: .percentageAdjustment)
      }
    }
  }

  /// A oneof that represents the different types for this adjustment.
  public enum OneOf_Adjustment: Codable, Equatable, Sendable {
    /// Flat markup or markdown on an entire bill.
    indirect case percentageAdjustment(PercentageAdjustment?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.RepricingAdjustment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
