// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Represents the various repricing conditions you can use for a conditional
/// override.
public struct RepricingCondition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Represents the types of existing conditional statements.
  public var condition: OneOf_Condition? = nil

  /// Initialize a new instance of `RepricingCondition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RepricingCondition().with { $0.skuGroupCondition = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case skuGroupCondition = "skuGroupCondition"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var condition: OneOf_Condition? = nil
    let conditionCheckAndSet = {
      if condition != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'condition'"))
      }
      condition = $0
    }
    if let skuGroupCondition = try container.decodeIfPresent(
      SkuGroupCondition?.self, forKey: .skuGroupCondition)
    {
      try conditionCheckAndSet(.skuGroupCondition(skuGroupCondition))
    }
    self.condition = condition
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.condition {
      switch choice {
      case .skuGroupCondition(let value):
        try container.encode(value, forKey: .skuGroupCondition)
      }
    }
  }

  /// Represents the types of existing conditional statements.
  public enum OneOf_Condition: Codable, Equatable, Sendable {
    /// SKU Group condition for override.
    indirect case skuGroupCondition(SkuGroupCondition?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.RepricingCondition"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
