// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for repricing a Google bill over a period of time.
public struct RepricingConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The YearMonth when these adjustments activate. The Day field
  /// needs to be "0" since we only accept YearMonth repricing boundaries.
  public var effectiveInvoiceMonth: GoogleType.Date? = nil

  /// Required. Information about the adjustment.
  public var adjustment: RepricingAdjustment? = nil

  /// Required. The [RebillingBasis][google.cloud.channel.v1.RebillingBasis] to
  /// use for this bill. Specifies the relative cost based on repricing costs you
  /// will apply.
  ///
  /// [google.cloud.channel.v1.RebillingBasis]: <doc:RebillingBasis>
  public var rebillingBasis: RebillingBasis = RebillingBasis()

  /// The conditional overrides to apply for this configuration. If you list
  /// multiple overrides, only the first valid override is used.  If you don't
  /// list any overrides, the API uses the normal adjustment and rebilling basis.
  public var conditionalOverrides: [ConditionalOverride] = []

  /// Required. Defines the granularity for repricing.
  public var granularity: OneOf_Granularity? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RepricingConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RepricingConfig().with { $0.entitlementGranularity = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let entitlementGranularity = CodingKeys(stringValue: "entitlementGranularity")
    static let channelPartnerGranularity = CodingKeys(stringValue: "channelPartnerGranularity")
    static let effectiveInvoiceMonth = CodingKeys(stringValue: "effectiveInvoiceMonth")
    static let adjustment = CodingKeys(stringValue: "adjustment")
    static let rebillingBasis = CodingKeys(stringValue: "rebillingBasis")
    static let conditionalOverrides = CodingKeys(stringValue: "conditionalOverrides")

    static let _knownKeys: Set<Swift.String> = [
      "entitlementGranularity",
      "channelPartnerGranularity",
      "effectiveInvoiceMonth",
      "adjustment",
      "rebillingBasis",
      "conditionalOverrides",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.effectiveInvoiceMonth = try container.decodeIfPresent(
      GoogleType.Date.self, forKey: .effectiveInvoiceMonth)
    self.adjustment = try container.decodeIfPresent(RepricingAdjustment.self, forKey: .adjustment)
    if let value = try container.decodeIfPresent(RebillingBasis.self, forKey: .rebillingBasis) {
      self.rebillingBasis = value
    }
    if let value = try container.decodeIfPresent(
      [ConditionalOverride].self, forKey: .conditionalOverrides)
    {
      self.conditionalOverrides = value
    }

    var granularity: OneOf_Granularity? = nil
    let granularityCheckAndSet = {
      if granularity != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'granularity'"))
      }
      granularity = $0
    }
    if let entitlementGranularity = try container.decodeIfPresent(
      RepricingConfig.EntitlementGranularity?.self, forKey: .entitlementGranularity)
    {
      try granularityCheckAndSet(.entitlementGranularity(entitlementGranularity))
    }
    if let channelPartnerGranularity = try container.decodeIfPresent(
      RepricingConfig.ChannelPartnerGranularity?.self, forKey: .channelPartnerGranularity)
    {
      try granularityCheckAndSet(.channelPartnerGranularity(channelPartnerGranularity))
    }
    self.granularity = granularity
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.effectiveInvoiceMonth, forKey: .effectiveInvoiceMonth)
    try container.encodeIfPresent(self.adjustment, forKey: .adjustment)
    try container.encode(self.rebillingBasis, forKey: .rebillingBasis)
    try container.encode(self.conditionalOverrides, forKey: .conditionalOverrides)

    if let choice = self.granularity {
      switch choice {
      case .entitlementGranularity(let value):
        try container.encode(value, forKey: .entitlementGranularity)
      case .channelPartnerGranularity(let value):
        try container.encode(value, forKey: .channelPartnerGranularity)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Applies the repricing configuration at the entitlement level.
  public struct EntitlementGranularity: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Resource name of the entitlement.
    /// Format:
    /// accounts/{account_id}/customers/{customer_id}/entitlements/{entitlement_id}
    public var entitlement: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EntitlementGranularity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EntitlementGranularity().with { $0.entitlement = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let entitlement = CodingKeys(stringValue: "entitlement")

      static let _knownKeys: Set<Swift.String> = [
        "entitlement"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entitlement) {
        self.entitlement = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.entitlement, forKey: .entitlement)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.channel.v1.RepricingConfig.EntitlementGranularity"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Applies the repricing configuration at the channel partner level.
  /// The channel partner value is derived from the resource name. Takes an
  /// empty json object.
  /// Deprecated: This is no longer supported. Use
  /// [RepricingConfig.EntitlementGranularity][google.cloud.channel.v1.RepricingConfig.EntitlementGranularity]
  /// instead.
  ///
  /// [google.cloud.channel.v1.RepricingConfig.EntitlementGranularity]: <doc:RepricingConfig/EntitlementGranularity>
  @available(*, deprecated)
  public struct ChannelPartnerGranularity: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ChannelPartnerGranularity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ChannelPartnerGranularity().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.channel.v1.RepricingConfig.ChannelPartnerGranularity"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Required. Defines the granularity for repricing.
  public enum OneOf_Granularity: Codable, Equatable, Sendable {
    /// Required. Applies the repricing configuration at the entitlement level.
    ///
    /// Note: If a
    /// [ChannelPartnerRepricingConfig][google.cloud.channel.v1.ChannelPartnerRepricingConfig]
    /// using
    /// [RepricingConfig.EntitlementGranularity][google.cloud.channel.v1.RepricingConfig.EntitlementGranularity]
    /// becomes effective, then no existing or future
    /// [RepricingConfig.ChannelPartnerGranularity][google.cloud.channel.v1.RepricingConfig.ChannelPartnerGranularity]
    /// will apply to the
    /// [RepricingConfig.EntitlementGranularity.entitlement][google.cloud.channel.v1.RepricingConfig.EntitlementGranularity.entitlement].
    /// This is the recommended value for both
    /// [CustomerRepricingConfig][google.cloud.channel.v1.CustomerRepricingConfig]
    /// and
    /// [ChannelPartnerRepricingConfig][google.cloud.channel.v1.ChannelPartnerRepricingConfig].
    ///
    /// [google.cloud.channel.v1.ChannelPartnerRepricingConfig]: <doc:ChannelPartnerRepricingConfig>
    /// [google.cloud.channel.v1.CustomerRepricingConfig]: <doc:CustomerRepricingConfig>
    /// [google.cloud.channel.v1.RepricingConfig.ChannelPartnerGranularity]: <doc:RepricingConfig/ChannelPartnerGranularity>
    /// [google.cloud.channel.v1.RepricingConfig.EntitlementGranularity]: <doc:RepricingConfig/EntitlementGranularity>
    /// [google.cloud.channel.v1.RepricingConfig.EntitlementGranularity.entitlement]: <doc:RepricingConfig/EntitlementGranularity/entitlement>
    indirect case entitlementGranularity(RepricingConfig.EntitlementGranularity?)
    /// Applies the repricing configuration at the channel partner level.
    /// Only
    /// [ChannelPartnerRepricingConfig][google.cloud.channel.v1.ChannelPartnerRepricingConfig]
    /// supports this value. Deprecated: This is no longer supported. Use
    /// [RepricingConfig.entitlement_granularity][google.cloud.channel.v1.RepricingConfig.entitlement_granularity]
    /// instead.
    ///
    /// [google.cloud.channel.v1.ChannelPartnerRepricingConfig]: <doc:ChannelPartnerRepricingConfig>
    /// [google.cloud.channel.v1.RepricingConfig.entitlement_granularity]: <doc:RepricingConfig/OneOf_Granularity/entitlementGranularity(_:)>
    @available(*, deprecated)
    indirect case channelPartnerGranularity(RepricingConfig.ChannelPartnerGranularity?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.RepricingConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
