// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Represents the type for a monetizable resource(any entity on which billing
/// happens). For example, this could be MINUTES for Google Voice and GB for
/// Google Drive. One SKU can map to multiple monetizable resources.
public enum ResourceType: Codable, Equatable, Sendable {
  /// Not used.
  case unspecified
  /// Seat.
  case seat
  /// Monthly active user.
  case mau
  /// GB (used for storage SKUs).
  case gb
  /// Active licensed users(for Voice SKUs).
  case licensedUser
  /// Voice usage.
  case minutes
  /// For IaaS SKUs like Google Cloud, monetization is based on usage accrued on
  /// your billing account irrespective of the type of monetizable resource. This
  /// enum represents an aggregated resource/container for all usage SKUs on a
  /// billing account. Currently, only applicable to Google Cloud.
  case iaasUsage
  /// For Google Cloud subscriptions like Anthos or SAP.
  case subscription
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .seat: return 1
    case .mau: return 2
    case .gb: return 3
    case .licensedUser: return 4
    case .minutes: return 5
    case .iaasUsage: return 6
    case .subscription: return 7
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "RESOURCE_TYPE_UNSPECIFIED"
    case .seat: return "SEAT"
    case .mau: return "MAU"
    case .gb: return "GB"
    case .licensedUser: return "LICENSED_USER"
    case .minutes: return "MINUTES"
    case .iaasUsage: return "IAAS_USAGE"
    case .subscription: return "SUBSCRIPTION"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ResourceType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "RESOURCE_TYPE_UNSPECIFIED": self = .unspecified
    case "SEAT": self = .seat
    case "MAU": self = .mau
    case "GB": self = .gb
    case "LICENSED_USER": self = .licensedUser
    case "MINUTES": self = .minutes
    case "IAAS_USAGE": self = .iaasUsage
    case "SUBSCRIPTION": self = .subscription
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ResourceType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .seat
    case 2: self = .mau
    case 3: self = .gb
    case 4: self = .licensedUser
    case 5: self = .minutes
    case 6: self = .iaasUsage
    case 7: self = .subscription
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .seat: return try container.encode(1)
    case .mau: return try container.encode(2)
    case .gb: return try container.encode(3)
    case .licensedUser: return try container.encode(4)
    case .minutes: return try container.encode(5)
    case .iaasUsage: return try container.encode(6)
    case .subscription: return try container.encode(7)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
