// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for
/// [CloudChannelReportsService.RunReportJob][google.cloud.channel.v1.CloudChannelReportsService.RunReportJob].
///
/// [google.cloud.channel.v1.CloudChannelReportsService.RunReportJob]: <doc:CloudChannelReportsServiceClient/runReportJob(request:options:)>
@available(*, deprecated)
public struct RunReportJobRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The report's resource name. Specifies the account and report used
  /// to generate report data. The report_id identifier is a UID (for example,
  /// `613bf59q`).
  /// Name uses the format:
  /// accounts/{account_id}/reports/{report_id}
  public var name: Swift.String = Swift.String()

  /// Optional. The range of usage or invoice dates to include in the result.
  public var dateRange: DateRange? = nil

  /// Optional. A structured string that defines conditions on dimension columns
  /// to restrict the report output.
  ///
  /// Filters support logical operators (AND, OR, NOT) and conditional operators
  /// (=, !=, <, >, <=, and >=) using `column_id` as keys.
  ///
  /// For example:
  /// `(customer:"accounts/C123abc/customers/S456def" OR
  /// customer:"accounts/C123abc/customers/S789ghi") AND
  /// invoice_start_date.year >= 2022`
  public var filter: Swift.String = Swift.String()

  /// Optional. The BCP-47 language code, such as "en-US".  If specified, the
  /// response is localized to the corresponding language code if the
  /// original data sources support it.
  /// Default is "en-US".
  public var languageCode: Swift.String = Swift.String()

  /// Initialize a new instance of `RunReportJobRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RunReportJobRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.RunReportJobRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
