// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents information which resellers will get as part of notification from
/// Pub/Sub.
public struct SubscriberEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Specifies the Pub/Sub event provided to the partners.
  /// This is a required field.
  public var event: OneOf_Event? = nil

  /// Initialize a new instance of `SubscriberEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SubscriberEvent().with { $0.customerEvent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case customerEvent = "customerEvent"
    case entitlementEvent = "entitlementEvent"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var event: OneOf_Event? = nil
    let eventCheckAndSet = {
      if event != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'event'"))
      }
      event = $0
    }
    if let customerEvent = try container.decodeIfPresent(
      CustomerEvent?.self, forKey: .customerEvent)
    {
      try eventCheckAndSet(.customerEvent(customerEvent))
    }
    if let entitlementEvent = try container.decodeIfPresent(
      EntitlementEvent?.self, forKey: .entitlementEvent)
    {
      try eventCheckAndSet(.entitlementEvent(entitlementEvent))
    }
    self.event = event
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.event {
      switch choice {
      case .customerEvent(let value):
        try container.encode(value, forKey: .customerEvent)
      case .entitlementEvent(let value):
        try container.encode(value, forKey: .entitlementEvent)
      }
    }
  }

  /// Specifies the Pub/Sub event provided to the partners.
  /// This is a required field.
  public enum OneOf_Event: Codable, Equatable, Sendable {
    /// Customer event sent as part of Pub/Sub event to partners.
    indirect case customerEvent(CustomerEvent?)
    /// Entitlement event sent as part of Pub/Sub event to partners.
    indirect case entitlementEvent(EntitlementEvent?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.SubscriberEvent"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
