// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specifies transfer eligibility of a SKU.
public struct TransferEligibility: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Whether reseller is eligible to transfer the SKU.
  public var isEligible: Swift.Bool = Swift.Bool()

  /// Localized description if reseller is not eligible to transfer the SKU.
  public var description: Swift.String = Swift.String()

  /// Specified the reason for ineligibility.
  public var ineligibilityReason: TransferEligibility.Reason = TransferEligibility.Reason()

  /// Initialize a new instance of `TransferEligibility`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferEligibility().with { $0.isEligible = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Reason of ineligibility.
  public enum Reason: Codable, Equatable, Sendable {
    /// Not used.
    case unspecified
    /// Reseller needs to accept TOS before transferring the SKU.
    case pendingTosAcceptance
    /// Reseller not eligible to sell the SKU.
    case skuNotEligible
    /// SKU subscription is suspended
    case skuSuspended
    /// The reseller is not authorized to transact on this Product. See
    /// https://support.google.com/channelservices/answer/9759265
    case channelPartnerNotAuthorizedForSku
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pendingTosAcceptance: return 1
      case .skuNotEligible: return 2
      case .skuSuspended: return 3
      case .channelPartnerNotAuthorizedForSku: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REASON_UNSPECIFIED"
      case .pendingTosAcceptance: return "PENDING_TOS_ACCEPTANCE"
      case .skuNotEligible: return "SKU_NOT_ELIGIBLE"
      case .skuSuspended: return "SKU_SUSPENDED"
      case .channelPartnerNotAuthorizedForSku: return "CHANNEL_PARTNER_NOT_AUTHORIZED_FOR_SKU"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Reason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REASON_UNSPECIFIED": self = .unspecified
      case "PENDING_TOS_ACCEPTANCE": self = .pendingTosAcceptance
      case "SKU_NOT_ELIGIBLE": self = .skuNotEligible
      case "SKU_SUSPENDED": self = .skuSuspended
      case "CHANNEL_PARTNER_NOT_AUTHORIZED_FOR_SKU": self = .channelPartnerNotAuthorizedForSku
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Reason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pendingTosAcceptance
      case 2: self = .skuNotEligible
      case 3: self = .skuSuspended
      case 4: self = .channelPartnerNotAuthorizedForSku
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pendingTosAcceptance: return try container.encode(1)
      case .skuNotEligible: return try container.encode(2)
      case .skuSuspended: return try container.encode(3)
      case .channelPartnerNotAuthorizedForSku: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.TransferEligibility"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
