// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [CloudChannelService.TransferEntitlements][google.cloud.channel.v1.CloudChannelService.TransferEntitlements].
///
/// [google.cloud.channel.v1.CloudChannelService.TransferEntitlements]: <doc:CloudChannelServiceClient/transferEntitlements(request:)>
public struct TransferEntitlementsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the reseller's customer account that will
  /// receive transferred entitlements. Parent uses the format:
  /// accounts/{account_id}/customers/{customer_id}
  public var parent: Swift.String = Swift.String()

  /// Required. The new entitlements to create or transfer.
  public var entitlements: [Entitlement] = []

  /// The super admin of the resold customer generates this token to
  /// authorize a reseller to access their Cloud Identity and purchase
  /// entitlements on their behalf. You can omit this token after authorization.
  /// See https://support.google.com/a/answer/7643790 for more details.
  public var authToken: Swift.String = Swift.String()

  /// Optional. You can specify an optional unique request ID, and if you need to
  /// retry your request, the server will know to ignore the request if it's
  /// complete.
  ///
  /// For example, you make an initial request and the request times out. If you
  /// make the request again with the same request ID, the server can check if
  /// it received the original operation with the same request ID. If it did, it
  /// will ignore the second request.
  ///
  /// The request ID must be a valid [UUID](https://tools.ietf.org/html/rfc4122)
  /// with the exception that zero UUID is not supported
  /// (`00000000-0000-0000-0000-000000000000`).
  public var requestId: Swift.String = Swift.String()

  /// Initialize a new instance of `TransferEntitlementsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferEntitlementsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.TransferEntitlementsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
