// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [CloudChannelService.UpdateChannelPartnerLink][google.cloud.channel.v1.CloudChannelService.UpdateChannelPartnerLink]
///
/// [google.cloud.channel.v1.CloudChannelService.UpdateChannelPartnerLink]: <doc:CloudChannelServiceClient/updateChannelPartnerLink(request:options:)>
public struct UpdateChannelPartnerLinkRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the channel partner link to cancel.
  /// Name uses the format: accounts/{account_id}/channelPartnerLinks/{id}
  /// where {id} is the Cloud Identity ID of the partner.
  public var name: Swift.String = Swift.String()

  /// Required. The channel partner link to update. Only
  /// channel_partner_link.link_state is allowed for updates.
  public var channelPartnerLink: ChannelPartnerLink? = nil

  /// Required. The update mask that applies to the resource.
  /// The only allowable value for an update mask is
  /// channel_partner_link.link_state.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateChannelPartnerLinkRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateChannelPartnerLinkRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.channel.v1.UpdateChannelPartnerLinkRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
